### ISSUE TITLE
Can I set a background image ?

### ISSUE THREAD

**Issue by QingMings** [NASAWorldWind/WebWorldWind#106]
Can I set the background image, it does not need to turn with the globel

**Comment by QingMings** [comment]
like this 
![image](https://cloud.githubusercontent.com/assets/22107668/24854209/26b88cf0-1e10-11e7-8c4b-2cb1610d4e30.png)

**Comment by strikerM** [comment]
You can set a background image to the canvas element with css.
`<canvas id="canvasOne" style="background-image: url('path/to/image');">`

We are also working on a StarField layer to show stars and the Sun in the "background". #86

**Comment by QingMings** [comment]
Thanks  ：)  ,very nice.
