### ISSUE TITLE
preventDefault doesn't work in the case of mouse leaving and entering the canvas with moudown

### ISSUE THREAD

**Issue by jaybarra** [NASAWorldWind/WebWorldWind#107]
Child of #508 

This issue shows up when the mouse is pressed while inside the canvas and is then dragged outside of the canvas and then returned to the canvas.

To replicate
1. add an event listener to `pointermove` and `mousemove` where it only fires preventDefault
```javascript
this.worldWindow.addEventListener('pointermove', function(event) {
  event.preventDefault();
});
this.worldWindow.addEventListener('mousemove', function(event) {
  event.preventDefault();
});
```
2. press and hold the left mouse button inside the canvas
3. drag the mouse outside of the canvas while still holding the mouse button
4. return the mouse to the canvas with the mouse still depressed

The map will now be dragging with the cursor. 
This affects Chrome and Firefox

**Comment by pdavidc** [comment]
@jaybarra Is this issue still relevant to you? If so, what is the intended use case? Our assessment is that the preventDefault mechanism was a poor design for attempting to disable WorldWind's default navigation responses, and we'd like to consider use cases in our ongoing work on navigation.
