### ISSUE TITLE
SurfaceShapes can re-appear when zooming after they have been removed from the map

### ISSUE THREAD

**Issue by jaybarra** [NASAWorldWind/WebWorldWind#109]
SurfaceShapes can re-appear on the map at different zoom levels after they have been removed from the all renderable layers.

They are removed successfully but when zooming out, especially at higher altitudes, they will re-appear then disappear as you continue to zoom out or back in.

**Comment by strikerM** [comment]
Same as #81 

This has been fixed in the develop branch.
Can you check with the develop branch?

**Comment by jaybarra** [comment]
Looks like it's fixed. Awesome, thanks
