### ISSUE TITLE
SurfaceShape ignores outlineWidth for highlightAttributes

### ISSUE THREAD

**Issue by strikerM** [NASAWorldWind/WebWorldWind#110]
Setting outlineWidth on highlightAttributes does nothing when the shape is highlighted.
This bug only affects the develop branch.

In SurfaceShape.prototype.renderToTexture
`ctx2D.lineWidth = 4 * this.attributes.outlineWidth;`
should be:
`ctx2D.lineWidth = 4 * attributes.outlineWidth;`

https://github.com/NASAWorldWind/WebWorldWind/blob/develop/src/shapes/SurfaceShape.js#L821
https://github.com/NASAWorldWind/WebWorldWind/blob/develop/src/shapes/SurfaceShape.js#L833

In the master branch we have:
`ctx2D.lineWidth = 4 * attributes.outlineWidth;`

If this fix is ok, I can prepare a pull request.

**Comment by pdavidc** [comment]
@strikerM, Thanks for identifying this bug. Given the scope of change, I'm comfortable with you committing the change directly.

Also, if you haven't done so already, would you please review SurfaceShape for any other instances of bugs like this?

**Comment by strikerM** [comment]
Made the changes.

I saw no other instances of this king of bug.

**Comment by Beak-man** [comment]
@strikerM solved the issue, closing the bug now.
