### ISSUE TITLE
Full sphere SurfaceSectors are not visible

### ISSUE THREAD

**Issue by jaybarra** [NASAWorldWind/WebWorldWind#112]
FULL_SPHERE SurfaceSectors are not visible on develop branch as of 
SHA 7651d90e82032cb598958509e2d2f06d90b94c5c

They do work on master at b1740c94a3dac66da9d99dceb04f2fb8b481e6a6

**Comment by AkeluX** [comment]
Unfortunately and as I was suspecting, the culprit is the new polygon splitter introduced in develop at c34bebb3f86b8fa403047c9d571af9380c2be082. @strikerM could you look at this issue and get back to us with a proposed way forward?

**Comment by strikerM** [comment]
The issue should be fixed in the develop branch. Commit  00765a124b29a0d079b0fb0b055f15d8a6883994
 @jaybarra when you get the chance, would you please verify that this issue is resolved?

**Comment by alberto-acevedo** [comment]
I tried latest code from the dev branch and it fixes the issue reported by Jay: setBackgroundBrightness is not working in WorldWind #280. 

Thanks

**Comment by AkeluX** [comment]
Thank you for the confirmation.
