### ISSUE TITLE
WMTS subdivision selection

### ISSUE THREAD

**Issue by jaybarra** [NASAWorldWind/WebWorldWind#113]
WMTS is not displaying correctly in WorldWind and an error is being thrown.

Service: https://basemap.nationalmap.gov/arcgis/rest/services/USGSShadedReliefOnly/MapServer/WMTS
Layer: USGSShadedReliefOnly
format: image/png

The error being thrown is "WmtsLayer.constructor: Tile subdivision not supported for layer : USGSShadedReliefOnly. Display until level 0"

WorldWind
![ww_wmts](https://cloud.githubusercontent.com/assets/25465248/25353997/2eeb2424-28ff-11e7-90c6-465e68379ca4.PNG)

Cesium Reference of the same WMTS service
![cesium_wmts](https://cloud.githubusercontent.com/assets/25465248/25353998/2eeba958-28ff-11e7-9654-f5f9f2220d01.PNG)

**Comment by zglueck** [comment]
@jaybarra thanks for the heads up.

We're restricted on the tiling scheme WebWorldWind supports currently, and while the NationalMap provides a tiling scheme which is compatible, we're not checking it properly before attempting to build the layer.

As a near term work around, if you set the config object used to create the WmtsLayer to the other TileMatrixSet provided by the NationalMap service (GoogleMapsCompatible), it will work.

I'm going to work from the [WMTS example](https://github.com/NASAWorldWind/WebWorldWind/blob/develop/examples/WMTS.js#L44) as a baseline:
```
       var createLayer = function (xmlDom) {
            // Create a WmtsCapabilities object from the XML DOM
            var wmtsCapabilities = new WorldWind.WmtsCapabilities(xmlDom);
            // Retrieve a WmtsLayerCapabilities object by the desired layer name
            var wmtsLayerCapabilities = wmtsCapabilities.getLayer(layerIdentifier);
            // Form a configuration object from the WmtsLayerCapabilities object
            var wmtsConfig = WorldWind.WmtsLayer.formLayerConfiguration(wmtsLayerCapabilities);
            // Create the WMTS Layer from the configuration object

            // Modify the config object to use a TileMatrixSet currently supported:
            wmtsConfig = wmtsLayerCapabilities.capabilities.contents.tileMatrixSet[1];

            var wmtsLayer = new WorldWind.WmtsLayer(wmtsConfig);

            // Add the layers to World Wind and update the layer manager
            wwd.addLayer(wmtsLayer);
            layerManger.synchronizeLayerList();
        }
```

This will get you around just the top level of imagery loading for this particular service. We need to conduct our tiling scheme check earlier in our configuration object creation.

**Comment by jaybarra** [comment]
Thanks, I'll give the workaround a shot

**Comment by alberto-acevedo** [comment]
@zglueck  , I tried the workaround of using  the google maps compatible tile matrix and I keep getting: "this.tileMatrixSet is undefined" line 81432 of worldwind.js. 

When I use the default028mm tile matrix, something renders on the map but with errors as already described by Jay.

I'm using the latest from the development branch.

Thanks.

**Comment by zglueck** [comment]
@alberto-acevedo, you may have already done this, but I believe my work around has a typo, it should be:

```
wmtsConfig.tileMatrixSet = wmtsLayerCapabilities.capabilities.contents.tileMatrixSet[1];
```

It must be the tileMatrixSet object and not just the identifier.

Let me know if you already tried this or if it still doesn't provide the work around you need for the near term.

**Comment by alberto-acevedo** [comment]
@zglueck , setting the tileMatrixSet to the google maps compatible tile matrix fixed the issue. Thanks.
