### ISSUE TITLE
PlacemarkAttributes doesn't have a vertical origin property.

### ISSUE THREAD

**Issue by alberto-acevedo** [NASAWorldWind/WebWorldWind#120]
I need a way to set the vertical origin of this placemark, which determines if the placemark is to the above, below, or at the center of its anchor position.

**Comment by pdavidc** [comment]
Have you tried imageOffset?

**Comment by alberto-acevedo** [comment]
The EMP map was reusing the imageOffset of the mil standard icon when switching to a dot placemark. Setting the dot image offset to .5, .5 fixed the issue. The issue was not in  WebWorldWind.   Thanks @pdavidc.
