### ISSUE TITLE
Apply the opacity of RenderableLayer to its renderables

### ISSUE THREAD

**Issue by AkeluX** [NASAWorldWind/WebWorldWind#134]
Following up on the forum topic at https://forum.worldwindcentral.com/forum/web-world-wind/web-world-wind-help/156834-layer-transparency-and-surface-elements and as discussed, it is proposed to apply the opacity value set on a RenderableLayer to its renderables making it possible to increase or decrease the transparency of all renderables at once.

The logic would be to multiply the opacity value of the renderable by the opacity value of the layer. For example:
Shapes opacity = 80%
Layer opacity = 50%
=> Shape rendered with opacity = 40%

**Comment by pdavidc** [comment]
@AkeluX Thank you for following up on the forum and creating this issue. As we discussed during today's ESA/NASA teleconference @NASAWorldWind/nasa-developers will follow up to make the necessary changes.

**Comment by eirizarry** [comment]
Closes #418.

**Comment by pdavidc** [comment]
@zglueck With #468 and #469 done, is there anything left to do to close this?

**Comment by zglueck** [comment]
@pdavidc, nothing left to do, this one is done!
