### ISSUE TITLE
KML line width not working

### ISSUE THREAD

**Issue by go717franciswang** [NASAWorldWind/WebWorldWind#137]
Hi,
In `KmlExample`, the line width is always very thin. For example, this [line](https://github.com/NASAWorldWind/WebWorldWind/blob/master/examples/data/KML_Samples.kml#L289) should have a width of 10.
Please let me know if there's any way to get around it.

Thanks,
Francis

**Comment by balhar-jakub** [comment]
Hello, 

If you are trying the example on Windows, there is known limitation of the WebGL implementation, which doesn't support Line Width other than 1 for lines.

Do you have any specific use case in mind to see whether there is some workaround?

**Comment by go717franciswang** [comment]
Got it. Thanks for pointing out the limitation. I'd like to build a widget to load KML file, and display hiking trails. The KML file uses `<LineString>` to mark trails, and shows up as a very thin line in WebWorldWind. I just read about this limitation on [WebGL doc](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/lineWidth). It suggested drawing a "strip of triangles". Should I modify the KML file to do this? Are there other workaround?

Thanks

**Comment by balhar-jakub** [comment]
The first question that is necessary to answer is: whether the lines need to be drawn in the air. 
If this isn't the case it is possible to use altitudeMode: clampToGround which interprets the lines as SurfacePolyline, which already process the drawing in a way which allows for different line width. 

The second set of options is based on the possibility to replace the implementation of KmlLineString and therefore reimplementation of its render method. 

- Simpler variant is that you will tweak the method to always use the SurfacePolyline regardless of the width of the line. 
- More complex variant is that you will provide your own rendering implementation that uses for example the approach you found in the article.

If you create the updated implementation of KmlLineString it is possible to replace it in the KML Rendering via following code:
WorldWind.KmlElements.addKey('LineString', NewKmlLineString);

**Comment by go717franciswang** [comment]
Awesome. Thanks for the instructions. I followed your first option and replaced [new Path(..)](https://github.com/NASAWorldWind/WebWorldWind/blob/689ee29cbc286560aedbe94738d96b782cd06699/src/formats/kml/geom/KmlLineString.js#L127) with `new SurfacePolyline(..)`. It's displaying the correct width now.
![Imgur](http://i.imgur.com/BWkNMw0m.png)
