### ISSUE TITLE
polygons with holes in GeoJSON are not implemented

### ISSUE THREAD

**Issue by kilsedar** [NASAWorldWind/WebWorldWind#138]
I downloaded OpenStreetMap data and converted it to GeoJSON using "osmtogeojson" (https://github.com/tyrasd/osmtogeojson). In case there are holes in polygons they are still polygons according to the GeoJSON specification (https://tools.ietf.org/html/rfc7946#section-3.1.6). However in the library, this is not implemented. 
To make polygons work, I had to comment out in "GeoJSONGeometryPolygon" lines 52-56, however, obviously the holes are filled.

**Comment by servetg** [comment]
Hi,

I've already solved this issue but I didn't trigger the pull request. Have
a look here:
https://github.com/NASAWorldWind/WebWorldWind/commit/4b7d330d47567a88981c8b8e45b5848ac4b2a68c
Please try with this fix and let me know if it works properly.

Thanks,
Servet

2017-06-18 2:01 GMT+03:00 kilsedar <notifications@github.com>:

**Comment by kilsedar** [comment]
Hi Server,
I tried your fix, but  I still get the "invalidLinearRing" error. 
However, I suppose you meant the if statement differently in GeoJSONGeometryPolygon.js.
It should be   `if (coordinates[i][0][0] !== coordinates[i][coordinates[i].length - 1][0] || coordinates[i][0][1] !== coordinates[i][coordinates[i].length - 1][1])`, then it works.

**Comment by servetg** [comment]
Oh yeah, you're right, my bad. I fixed.
Thanks!

**Comment by kilsedar** [comment]
Great, thank you!
