### ISSUE TITLE
Test Web WorldWind npm mockup as a node module

### ISSUE THREAD

**Issue by Beak-man** [NASAWorldWind/WebWorldWind#139]
Web WorldWind is as of now being tested as an [npm package](https://www.npmjs.com/package/test-web-world-wind). It's interoperability with other frameworks that operate under npm (e.g. React) will be tested as well. Such frameworks need some [special considerations](https://youtu.be/GWVjMHDKSfU) to integrate third-party libraries that are not present as node modules in npm, as is the case with the worldwind.js library at this moment. With the automation of npm publishing, we aim to ease the inclusion of the library as a package in bigger projects for front-end developers.

**Comment by Beak-man** [comment]
As of now, the mockup Web WorldWind npm package does little else than publishing the library artifacts (worldwind.js and worldwind.min.js) and the required assets (namely, the /images folder) in the node_modules folder, with no module exposition in a CommonJS-like environment.

A simple 'module.exports' implementation wouldn't suffice as Web WorldWind is not meant to be loaded with Node alone as it doesn't work without the DOM. The jQuery community [came up with a solution](https://bugs.jquery.com/ticket/14549) so their DOM library operates both with CommonJS in the browser (for instance, to use it under browserify), and under Node as long as a window object is used as an argument (e.g. with this object created by a Node implementation like [jsdom](https://www.npmjs.com/package/jsdom)).

**Comment by Beak-man** [comment]
The test npm package for Web Worldwind should now work as a true npm module (i.e. with a CommonJS interface). The worldwind.js library exposes itself as follows:

![commonjs](https://user-images.githubusercontent.com/7622894/27551235-34c36272-5a68-11e7-918a-7568904132a2.png)

**Comment by pdavidc** [comment]
@Beak-man Did the npm mockup excersise involve WebWorldWind components the rely on content in the images directory?

**Comment by pdavidc** [comment]
@Beak-man I'd like to perform this test within our new nasaworldwind NPM organization. Would you please try publishing the mockup node module "test-nasa-world-wind" to our organization?

**Comment by Beak-man** [comment]
@pdavidc , yeah, the mockup has the image assets.

And sure, I'll publish the test package in the following minutes.

**Comment by Beak-man** [comment]
@pdavidc `test-web-world-wind` is now published to our [npm organization](https://www.npmjs.com/org/nasaworldwind) but now I'm seeing a disadvantage with npm orgs. They complicate the package installation command by adding the organization name as a suffix. As it is now, installing needs to be done with `npm i @nasaworldwind/test-web-world-wind`. According to [npm docs](https://docs.npmjs.com/misc/scope), this stems from the purpose of [npm organizations](https://docs.npmjs.com/misc/orgs), which is to provide institutions with private registries, that are of course unneeded in our case.

I'll see if we can remove the suffix from the installation command. If not, I would suggest dropping the npm organization altogether and just making the package a plain org-less module with team collaborators.

**Comment by pdavidc** [comment]
Thanks for testing and catching this. Complicating the npm install would indeed be a serious disadvantage. I agree with your observation that most modules appear to be published by individuals. We needed to learn whether this was due to free npm organizations being a recently added feature, or some other reason.

Let me know what you find about removing the org namespace from the installation command. If that's not possible we'll proceed as you suggest. In that case I'll need to be the one that publishes the official package named "worldwind".

**Comment by Beak-man** [comment]
> While you get a scope by default when registering as an Org, that doesn't mean you have to use it. In fact, you can use Orgs to manage unscoped packages, or even packages under a different scope, such as a user scope, e.g. @ag_dubs/hello, where ag_dubs is an npm user.

https://www.npmjs.com/docs/orgs/

Nice. How to do it is further hidden somewhere in the docs. I'll keep looking.

**Comment by Beak-man** [comment]
Testing underway with the [React starter kit](https://github.com/kriasoft/react-starter-kit). See #157

**Comment by pdavidc** [comment]
After carefully considering WorldWind's plans for other NPM packages, we've become convinced that org-scoped package are a good thing for WorldWind. Given that, we need to validate that org-scoped packages work with the app developer tools we want to support.

**Comment by Beak-man** [comment]
Testing with the [mockup](https://www.npmjs.com/package/test-web-world-wind) is finished. I've removed it from our npm organization. The package that can be generated with latest commit in the feature/npm branch is working inside a [test project](https://github.com/Beak-man/worldwind-react), but only unscoped. It's not loading local image files either. I'm pretty confident that it can be made to work with scoping, though.
