### ISSUE TITLE
Set up Travis-CI environment

### ISSUE THREAD

**Issue by Beak-man** [NASAWorldWind/WebWorldWind#144]
The build process will be reviewed in Travis before implementing npm publishing via CI. By this time, the generated artifacts will be CommonJS-compliant for them to be ready for npm. No npm publishing will be done automatically at this point, since package versioning requires further steps in order to be automated.

**Comment by pdavidc** [comment]
@Beak-man just a heads up that after you complete work on #143, I'd like to work on the Travis CI setup for WebWW. If you're interested in getting more experience with Travis CI, we could certainly collaborate.

**Comment by Beak-man** [comment]
@pdavidc gladly! #143 pull request is up for review. I need to add the npm publishing stuff before Travis, though (#151) but I have everything now. It should be very quick if the pull request is up to standards.
