### ISSUE TITLE
Handle versioning of npm package in Travis-CI

### ISSUE THREAD

**Issue by Beak-man** [NASAWorldWind/WebWorldWind#145]
Closes #136 

Since the npm registry is opinionated on how it handles versions (i.e. it uses [semantic versioning](https://docs.npmjs.com/getting-started/semantic-versioning)), the step of updating the version number is required before publishing to npm. The usual method for updating the version number is with 'npm version', but [there are tools](https://stackoverflow.com/questions/13059991/update-package-json-version-automatically) that [facilitate](https://conventionalcommits.org/) this, even taking advantage of Git commit tags. Options will be considered to automate this crucial part of the process.

**Comment by zglueck** [comment]
If we plan to release in a similar workflow to WWA, I think we'll need to use a modification of `npm version`. By default, `npm version patch` bumps the patch integer, creates a commit and tag; however, we can just bump the version by `npm version patch --no-git-tag-version`.

From my investigation, using `npm version` with the `--no-git-tag-version` option updates the version number in the `package.json` and `package-lock.json` files. This could be done manually as well.

Just for quick reference: [npm version](https://docs.npmjs.com/cli/version)

**Comment by pdavidc** [comment]
Let's think about this from the point of view of WebWorldWind's release workflow. The authoritative release version is defined in our Git tag. Given that, I don't see how npm version's automatic increment is of any use to us.

**Comment by zglueck** [comment]
For upcoming releases, manually editing the file best fits into our release workflow.
