### ISSUE TITLE
Investigate whether external libraries in src/util can be refactored as npm dependencies

### ISSUE THREAD

**Issue by Beak-man** [NASAWorldWind/WebWorldWind#147]
Some of the libraries that WebWW utilizes may not exist in the npm registry, but it could be worthwhile to refactor the ones that do exist as npm packages to provide better dependency management.

**Comment by Beak-man** [comment]
npm packages for every 3rd party library that is currently in src/util were found.

es6-promise -> https://www.npmjs.com/package/es6-promise
proj4-src -> https://www.npmjs.com/package/proj4
jszip -> https://www.npmjs.com/package/jszip
libtess -> https://www.npmjs.com/package/libtess

**Comment by Beak-man** [comment]
Doing this would require changing our bundling mechanism, since RequireJS is not able to load CommonJS Node modules. Browserify can bundle projects with AMD and CommonJS modules with plugins, and Webpack is able to do all of them from the get go, even implementing ES6 modules. A newer option, SystemJS also exists.

A comparison between the four bundling tools can be found here: https://youtu.be/ahRNMEA4mWw

It could be worthwhile to consider an epic to change Web WorldWind's bundling methods. Besides providing us with dependency management for the 3rd party libraries that we require, it would also provide Web WorldWind with a 'standard' interface for extensions via npm packages.

**Comment by pdavidc** [comment]
Very nice summary and explanatory video. Given your findings I agree with the decision to close this issue now, with the option consider an epic for changing the bundling mechanism in the future.

**Comment by Beak-man** [comment]
New bundlers in the ever-changing JavaScript world:

https://parceljs.org/ - Supports CommonJS and ES6 module types.
https://rollupjs.org/ - Focused on bundling ES6 modules. Supports CommonJS and AMD modules through 3rd party plugins (https://www.npmjs.com/package/rollup-plugin-amd).

Guide on how to bundle ES6 modules alongside older definitions:
https://hackernoon.com/7-different-ways-to-use-es-modules-today-fc552254ebf4

**Summary:** 
Handling different JS module definitions is still quite sketchy and full of pitfalls. 

Support for the only official module type (ES6) is just partially being rolled out to major web browsers, thus new module bundlers seem to focus on enabling ES6 usage (basically becoming ES6 polyfills). That being said, support for CommonJS modules is still highly sought after, due to the prevalence of npm packages.

AMD modules are becoming really long in the tooth, and few people seem to care about ensuring supporting them in current projects.
