### ISSUE TITLE
Establish WorldWind npm organization

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WebWorldWind#150]
Create a WorldWind organization on https://npmjs.com and invite the NASAWorldWind organization members to join.

**Comment by pdavidc** [comment]
Created a "nasaworldwind" organization on npmjs.org. We're using the open source tier, which is free and requires that all projects are public. I chose the name "nasaworldwind" in order to match the organization names on GitHub and Bintray. Here's a list of the public open source organizations the NASA World Wind project now uses:

https://github.com/nasaworldwind
https://bintray.com/nasaworldwind
https://npmjs.com/org/nasaworldwind

**Comment by pdavidc** [comment]
@emxsys and @zglueck create profiles on npmjs.com and I'll invite you to the organization.

**Comment by zglueck** [comment]
@pdavidc I'm zglueck on npmjs.com
