### ISSUE TITLE
Test for differences between scoped and unscoped npm package release

### ISSUE THREAD

**Issue by Beak-man** [NASAWorldWind/WebWorldWind#159]

**Comment by Beak-man** [comment]
I found out that [it is possible to build npm packages without publishing them](http://podefr.tumblr.com/post/30488475488/locally-test-your-npm-modules-without-publishing), and with this I've been testing a scoped and unscoped version of our package in [my React tester](https://github.com/Beak-man/worldwind-react). The scoped version is refusing to load, even though I've seen projects with Angular's scoped packages everywhere.

**Comment by pdavidc** [comment]
Thanks for beginning testing on this. I assume you'll be doing more testing and diagnosis during the current sprint. Does it make any difference if the scoped npm package is published?

**Comment by Beak-man** [comment]
In theory, it shouldn't make any difference, but I'll try. I published [another Web WorldWind package in here](https://www.npmjs.com/package/webww), which is based off the feature/npm branch code (instead of the mockup which was a fork in order to test Travis in it). I'll scope it and test it. And yes, I'm following up with testing with scoping in this sprint.

**Comment by Beak-man** [comment]
After testing the scoped package in the aforementioned React tester, a separate Webpack basic project and even inside the Node command-line runtime, I found out that the problem was with the package's entry script naming inside `package.json`.

This is how the header for our `package.json` file looked like when it was failing:
```javascript
{
  "name": "@nasaworldwind/worldwind",
  "version": "0.0.1",
  "description": "Web WorldWind",
  "main": "worldwind.min.js",
  "homepage": "https://nasaworldwind.github.io/",
  "bugs": {
    "url": "https://github.com/NASAWorldWind/WebWorldWind/issues"
  }
```
The problem was with the 'main' attribute, which states the entry point for the package. [When creating an npm package, this defaults to `index.js`](https://docs.npmjs.com/getting-started/creating-node-modules), but it can be changed, which I did in order to point it to either of our library files (`worldwind.min.js` or `worldwind.js`). This worked OK with unscoped packages, and it took me a while to find that, with scoped packages, the entry script has to be named `index.js`. [This issue](https://github.com/webpack/webpack/issues/3939) pointed me towards that, but it's not something that I see in npm's documentation.

So what was done was to install [another Grunt plugin](https://github.com/gruntjs/grunt-contrib-copy) in order to add the following steps to the build process:

- Copy the minified version of the library (worldwind.min.js)
- Rename that copy to `index.js`

The `index.js` file is therefore a new, if redundant, build artifact.

And now our `package.json` header looks like this:
```javascript
{
  "name": "@nasaworldwind/worldwind",
  "version": "0.0.1",
  "description": "Web WorldWind",
  "main": "index.js",
  "homepage": "https://nasaworldwind.github.io/",
  "bugs": {
    "url": "https://github.com/NASAWorldWind/WebWorldWind/issues"
  }
```
The npm package now works OK with the [React tester in my repo](https://github.com/Beak-man/worldwind-react). The package is included as a .tgz file for now, until we officially release it.

I will contact npm regarding this apparent inconsistency regarding the '"main":' attribute. It looks like an oversight. Their support has been great.
