### ISSUE TITLE
Goto location hangs up without error

### ISSUE THREAD

**Issue by bangph** [NASAWorldWind/WebWorldWind#167]
I have a simple case with 2 divs (canvas) to initialize 2 WorldWind object and stored in an array. So both of divs can display the Globe which I can turn it around, zoom in, zoom out,...

However, when I create a function to load a polygon (same polygon to both Globes) and with the Goto to go the center point of polygon. Both of Globes will hang up (cannot zoom or move), it will stick the view at this center point (I can move or zoom in/out a little bit, but after that, the Globe returns back to the center point without reason). If I don't use the goto localtion method of WebWorldWind then no problem of moving, zoom the Globe.

I'm using Angularjs 1.4 and the newest version of WebWorldWind from http://worldwindserver.net/webworldwind/worldwind.min.js

Here is the code for the method to Goto the center point of polygon

`// Go to the center of the first coverage extent of the input array on Globe
        public gotoCoverageExtentCenter(canvasId: string, coverageExtents: any) {
            var webWorldWindModel = null;            
            for (var i = 0; i < this.webWorldWindModels.length; i++) {
                if (this.webWorldWindModels[i].canvasId === canvasId) {                    
                    webWorldWindModel = this.webWorldWindModels[i];
                    break;
                }
            }
            var coverageExtent = coverageExtents[0];
            var xcenter = (coverageExtent.bbox.xmin + coverageExtent.bbox.xmax) / 2;
            var ycenter = (coverageExtent.bbox.ymin + coverageExtent.bbox.ymax) / 2;
            var wwd = webWorldWindModel.wwd;            

            // NOTE: this one makes the Globe hang up multiple times.
            // wwd.goTo(new WorldWind.Location(ycenter, xcenter));                                                                    
        }`

**Comment by bangph** [comment]
@AkeluX

**Comment by balhar-jakub** [comment]
I was trying to reproduce this issue and was unsuccessful. I was trying in the Chrome and Firefox. 

I tried adding following code at the end of the MultiWindow.js example
Variant1:
    setTimeout(function(){
        wwd1.goTo(new WorldWind.Location(10, 15));
        wwd2.goTo(new WorldWind.Location(10, 15));
        wwd3.goTo(new WorldWind.Location(10, 15));
    }, 10000)

Variant2:
        wwd1.goTo(new WorldWind.Location(10, 15));
        wwd2.goTo(new WorldWind.Location(10, 15));
        wwd3.goTo(new WorldWind.Location(10, 15));

Variant3: 
    setTimeout(function(){
        wwd1.goTo(new WorldWind.Location(10, 15));
    }, 1000)

   setTimeout(function(){
        wwd2.goTo(new WorldWind.Location(10, 15));
    }, 2000)

    setTimeout(function(){
        wwd3.goTo(new WorldWind.Location(10, 15));
    }, 3000)

Could you please try whether following code will work for you?
wwd.navigator.lookAtLocation = new WorldWind.Location(ycenter, xcenter); 
wwd.redraw();
instead of the
wwd.goTo(new WorldWind.Location(ycenter, xcenter));

It might also be useful to know the operating system and the browser under which this issue occurs.

**Comment by bangph** [comment]
Thank a lot for your quick reply and detail. I tried your suggestion and it worked without the iterating error. 
I also prefer this lookAtLocation property as it does not need to wait for the Globe moves to to the location like the goTo() method.

Also, in the worst case of goTo() the Globe will crash and the screen will blink with only the color of the map and I have to close the Chrome tab as refresh the tab does not work (the loading icon shows in the tab).
