### ISSUE TITLE
Image asset packaging and hosting

### ISSUE THREAD

**Issue by zglueck** [NASAWorldWind/WebWorldWind#170]
The images directory in the repository should be available for separate download. This will allow users to package or access the assets in a manner compatible to their deployment environment.

**Comment by zglueck** [comment]
@pdavidc, @Beak-man, I'd like to get your evaluation on my initial findings.

## Options for packaging

The goal was to find a minimal complexity method to provide the images directory and an images.zip. This will provide flexibility in different target deployment environments.

For packaging the images directory into a .zip, I recommend either:
1. grunt compress task
2. travis zip command

Either will accomplish the task, I recommend adding it as a grunt task, primarily because it keeps the preparation for `npm publish` identical between our CI and development environments.

## Options for hosting

As expected, there are a number of hosting options for the zip and image files. I think one option satisfies all of the requirements and more, https://unpkg.com.

unpkg.com basically provides a browsable representation of npm packages. Check out @Beak-man 's test module: https://unpkg.com/webww/

Did you notice the sweet automatic redirect to the latest version in the url? You can also specify versions using the same qualifiers as npm (e.g. ^). The content is hosted on a CDN and doesn't require any special setup on our side.

As a bonus, the images directory is available as well, and unpkg.com sets the `Access-Control-Allow-Origin` header to `*`!

Combined, this means we have a CDN backed zip distribution, but also have a CDN hosting for the libraries. But wait there is more, because the plain images directory is also provided, users can still just add the library as a script tag (e.g. `<script src="https://unpkg.com/webww/worldwind.min.js"></script>` and, because the images are in the expected directory and we are getting the wild card CORS access, they appear automatically!

Alternatives for hosting could be Bintray; however, the images directory would not work as they don't set the CORS header, the images.zip would work fine for downloading. We could also provide the zip contents as part of the release in GitHub, similarly to how we've distrubuted WWJ and formerly WWA.

## Communicating to developers

I know @eirizarry has the best handle on the final version of this, but wanted to put a draft "how to" or "get started" together:

---

## Get Started

There are a few options for integrating Web WorldWind with our webpage. The most common ways are list below. For integrating the HTML5 canvas and adding content, please see the [Tutorials](https://google.com).

### Download

Download the debug or minified versions of the Web WorldWind library:

[worldwind.min.js](https://unkpg.com/webww/worldwind.min.js)
[worldwind.js](https://unpkg.com/webww/worldwind.js)

*and*

grab [images.zip](https://unpkg.com/webww/images.zip) and place at the root of your site to provide the compass, and view control buttons (this isn't required if you don't plan on using the compass or view control buttons).

### Using a hosted version

Include the following script source on your webpage:
```html
<script src="https://unpkg.com/webww/worldwind.min.js"></script>
```

### npm

Use npm for installation and application development with different module definitions (AMD, CommonJS, ES6) through Webpack and RequireJS.

```
npm install webww
```

### Building the library

Building the library requires npm.

1. Clone the Web WorldWind Repository from GitHub: `git clone https://github.com/NASAWorldWind/WebWorldWind.git`
2. Install the dependencies: `npm install`
3. Build the worldwind.js and worldwind.min.js files: `npm run build`
4. Add the worldwind.js or worldwind.min.js files to your websites resources

**Comment by Beak-man** [comment]
Nice job! Unpkg seems the way to go and the image delivery method is simple enough.

As opposed to what's on the webww package, in the feature/npm branch I removed  worldwind.js and worldwind.min.js, since I considered them redundant after bundling the new 'index.js' copy of worldwind.min.js to solve scoping, and I didn't had in in mind unpkg's CDN at the time.

I'll add them again. They're not increasing the download size in a significant manner.

**Comment by zglueck** [comment]
@Beak-man hadn't thought of that. We could always change the link to point at index.js, but I think it is more conventional to use the module name for script links.

**Comment by Beak-man** [comment]
I agree. I hope npm's support sorts out the entry script name overriding in scoped packages so we can get rid of index.js. The usual artifacts are back now, alongside index.js. Maybe reconsidering making it a shim is a good idea?

**Comment by pdavidc** [comment]
@zglueck Thanks for this analysis of our options. Unpkg does indeed seem the best choice given our two use cases: link to the library via CDN; download the images for npm.

How does Unpkg handle scoped npm packages?

**Comment by pdavidc** [comment]
@Beak-man You're right to keep worldwind.js and worldwind.min.js in the npm package. Since index.js is a workaround, we need to keep the original artifacts, regardless of whether we end up using Unpkg. 

Let's keep any further discussion with regard to the JS artifacts in that thread. Retracing our steps is difficult when information is spread across multiple issues.

**Comment by zglueck** [comment]
@pdavidc , scoped packages are just an additional path entry in the url:

https://unpkg.com/@angular/core@5.0.0-beta.0/@angular/core.js

**Comment by pdavidc** [comment]
Thanks for clarifying. Let's finish the review for #171, then have you submit a pull request for the necessary Grunt changes.
