### ISSUE TITLE
Load restlayer unsuccessfully

### ISSUE THREAD

**Issue by yjsh824** [NASAWorldWind/WebWorldWind#184]
I load a resylayer of ESRI's like this 'http://services.arcgisonline.com/arcgis/rest/services/ESRI_Imagery_World_2D/MapServer'.
codes:

        var config={
            levelZerotTileDelta:new WorldWind.Location(90,-180),
             numLevels:16,
            imageFormat : "image/jpeg",
            tileWidth:512,
            tileHeight:512
        };
        var url="http://services.arcgisonline.com/arcgis/rest/services/ESRI_Imagery_World_2D/MapServer";
        var restlayer1=new WorldWind.RestTiledImageLayer(url,"tile","Layers",config);

As the result,the world's tiles only Overlay in Antarctic Circle。
Who can tell me how to solve this question?Thanks!~

**Comment by pdavidc** [comment]
@yjsh824 Is this issue still relevant to you? If so, the config object's levelZeroTileDelta is incorrect. While the tile delta is expressed as a location, its latitude and longitude indicate the top level tile size in geographic coordinates, and not the tile origin.
