### ISSUE TITLE
GestureRecognizer on Mozilla Firefox

### ISSUE THREAD

**Issue by kilsedar** [NASAWorldWind/WebWorldWind#185]
I noticed that all the subclasses of GestureRecognizer class do not work on Mozilla Firefox. Is there a fix for this issue?
Thanks.

**Comment by pdavidc** [comment]
Would you please send us more detail, including:
- Operating system 
- Firefox version
- Log output (if you're able)

**Comment by kilsedar** [comment]
I am using Ubuntu 16.04.
Firefox version: 54.0 (64-bit).
After further investigation, only for two of the subclasses of GestureRecognizer, DragRecognizer and ClickRecognizer which are the ones I suppose for desktop, here are my conclusions. ClickRecognizer works if the target is the WorldWindow itself on Firefox (as it happens at http://worldwindserver.net/webworldwind/examples/GoToLocation.js). However in this case DragRecognizer doesn't work. On Chrome, the same happens.
If I change the target to WorldWindow.canvas, both works on Chrome and neither works on Firefox. 
I also find referring the target as "document element" confusing, as it suggests canvas in my opinion more that the WorldWindow. 
Note: to check if they work or not, I am simply logging in the console in the callback of the recognizers.

**Comment by pdavidc** [comment]
@kilsedar Is this issue still relevant for you, and is it still reproducible?
