### ISSUE TITLE
CompoundElevationModel

### ISSUE THREAD

**Issue by alienatorZ** [NASAWorldWind/WebWorldWind#20]
I would like to request a feature to compose elevations similar to the CompoundElevationModel found in WWJ.

Thanks!

**Comment by pdavidc** [comment]
Thanks for the request. We would very much like to incorporate CompoundElevationModel into WebWW. It's on our long term roadmap.

**Comment by AkeluX** [comment]
FYI. We've started looking into a CompoundElevationModel, but no timeline yet.

**Comment by pdavidc** [comment]
We've started work on support for multiple elevation coverages in WebWW. The result will be a web-appropriate capability for composing elevations similar to WWJava's CompoundElevationModel. Follow epic #422 for details.
