### ISSUE TITLE
TectonicPlatesLayer overwrites the attributes property of the SurfacePolygon

### ISSUE THREAD

**Issue by balhar-jakub** [NASAWorldWind/WebWorldWind#208]
### Description

When I try to set attributes of the SurfacePolygon it fails on the TectonicPlatesLayer attributes setter as the array of renderables for the SurfacePolygon doesn't exist at any moment other than when used as a part of the TectonicPlatesLayer

### Steps to Reproduce

Following simplified code from the SurfaseShapes example produces this error but initially, I ran into it in the WktParser generating the SurfaceShapes.

        var boundary = [new WorldWind.Location(40, -100), new WorldWind.Location(45, -110), new WorldWind.Location(40, -120)];

        var attributes = new WorldWind.ShapeAttributes(null);
        attributes.outlineColor = WorldWind.Color.BLUE;

        var shape = new WorldWind.SurfacePolygon(boundary, null);
        shape.attributes = attributes; // Added line
        shapesLayer.addRenderable(shape);

**Expected behavior:** [What you expect to happen]

The attributes will be correctly set

**Actual behavior:** [What actually happens]

Actual behavior is that the error from the TectonicPlatesLayer is raised. 
Uncaught TypeError: Cannot read property 'map' of undefined
    at SurfacePolygon.set (TectonicPlatesLayer.js:65)
    at WktParser.js:78
    at Array.forEach (<anonymous>)
    at WktParser.js:75
    at Array.forEach (<anonymous>)
    at WktParser.load (WktParser.js:74)
    at Wkt.js:30
    at Object.execCb (require.min.js:1)
    at Module.check (require.min.js:1)
    at Module.<anonymous> (require.min.js:1)

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Operating System and Version

Windows 10, Chrome

### Additional Information

The fix should be simply to change this line (53) in TectonicPlatesLayer
Object.defineProperties(SurfacePolygon.prototype, {
to this:
Object.defineProperties(RenderableLayer.prototype, {

**Comment by pdavidc** [comment]
Closed via #116
