### ISSUE TITLE
2d drag issue

### ISSUE THREAD

**Issue by strangerintheq** [NASAWorldWind/WebWorldWind#209]
2d globe dragging seems to be broken
direction of dragging is wrong when i trying to drag the surface with high zoom in

**Comment by zglueck** [comment]
see also #61

**Comment by strangerintheq** [comment]
adding following patch fixes this problem for me

LookAtNavigator.prototype.handlePanOrDrag = function(recognizer) {
    this.handlePanOrDrag3D(recognizer);
};
