### ISSUE TITLE
about the GeoTiffReader.js

### ISSUE THREAD

**Issue by const-Ly** [NASAWorldWind/WebWorldWind#210]
about the getMetadataFromGeoKeys method of the GeoTiffReader.js file, why didn't you find the value of this.geoKeys? No assignment is given to this.geoKeys.

**Comment by Liuyongg** [comment]
The getMetadataFromGeoKeys method cannot be executed

**Comment by claudiaifrim** [comment]
It seems that the method getMetadataFromGeoKeys is obsolete code.
You can access metadata keys using the metadata attribute of the GeoTiffReader object.

**Comment by claudiaifrim** [comment]
See pull request https://github.com/NASAWorldWind/WebWorldWind/pull/446
