### ISSUE TITLE
Review Artifactory scanning results

### ISSUE THREAD

**Issue by zglueck** [NASAWorldWind/WebWorldWind#213]
Review the results of scanning and determine path forward for finalizing instance. This will provide a high confidence in the ability to host Artifactory pending the allocation of a dedicated VM and domain.

**Comment by pdavidc** [comment]
@RandolphKim what's the status of scanning our Artifactory instance?

**Comment by zglueck** [comment]
There have been no scan results provided. The Artifactory instance is now available at a new domain with corresponding SSL certificate.
