### ISSUE TITLE
Deep Picking Performance

### ISSUE THREAD

**Issue by AkeluX** [NASAWorldWind/WebWorldWind#230]
This issue is to summarise our current thoughts about the performance of deep picking. Feel free to contribute.

Deep picking is and must be a synchronous operation. As such, it blocks the main thread and impacts the rendering operations. With a significant number of shapes (1000+), deep picking time increases drastically to hundreds of milliseconds thus rendering the globe unusable.

Here are some ideas:

- Improve the intrinsic performance of deep picking, e.g. by changing the algorithm, less iterations, less exchanges between the CPU and GPU, combining colors;
- In the cases we have so far, this large number of shapes are surface shapes, we could thus offer an additional method for geometric picking of surface shapes instead of rendering for picking. With this solution, the mathematical operations could even be delegated to a WebWorker if too heavy;
- Throttling pick operations to guarantee that at least a render cycle happens in between.

The last point has already been tried and doesn’t provide enough benefits for being integrated as part of the core.

**Comment by pdavidc** [comment]
@AkeluX I've labelled this as an epic. The NASA team will be investigating solutions during our next sprint. We'll associate the various sub-tasks with this epic.

**Comment by markpet49** [comment]
Implementing pick frustum culling for deep picking resulted in a respectable performance improvement. Results are summarized below.

### Performance test results
Browser: Chrome
OS: Ubuntu
Performance numbers are approximate.

#### Deep Picking Performance prior to Enhancement
Number of shapes under cursor | 0 | 250 | 500 | 1000
-|-:|-:|-:|-:
Frame time (ms) | 3 | 700 | 700 | 700
Frame rate (FPS) | 170 | 1 | 1 | 1

#### Deep Picking Performance after Enhancement

Number of shapes under cursor| 0 | 250 | 500 | 1000
-|-:|-:|-:|-:
Frame time (ms) | 3 | 160 | 450 | 700
Frame rate (FPS) | 170 | 6 | 2 | 1

**Comment by AkeluX** [comment]
@markpet49 is the code of the enhanced version available somewhere? I'd like to have a look at the improvement for my use case. Thanks.

**Comment by markpet49** [comment]
@AkeluX The enhancement is merged into the develop branch. There is a demo in the performance folder called DeepPickingPerformance that I used for the performance metrics. I did find an issue yesterday that causes problems when switching globes, so bear that in mind. As long as you stay with the same projection while running, you'll be OK. I hope to have the projection issue fixed today.

**Comment by AkeluX** [comment]
Thanks. I'll try this out with my use case as well.
