### ISSUE TITLE
PNG rendered with blur effect

### ISSUE THREAD

**Issue by devsf** [NASAWorldWind/WebWorldWind#243]
Hi all,
I have to show pixeled-PNGs on WWW but it seems that WWW applys a strange blur effect (as you can see [here](https://forum.worldwindcentral.com/filedata/fetch?photoid=157925)).

The image is rendered with the SurfaceImage class, as shown in the SurfaceImage example (http://worldwindserver.net/webworldwind/examples/SurfaceImage.html).

Here you can find:
- the png: https://cloud.services.meeo.it/f/e350597f4a294b5a95e7/
- the aux: https://cloud.services.meeo.it/f/10e32fb2fc834b84bc19/

I've already asked on the forum: https://forum.worldwindcentral.com/forum/web-world-wind/web-world-wind-help/157924-png-rendered-with-blur-effect

Could you help me?

Thanks, bye!
Sergio

**Comment by AkeluX** [comment]
Hi @devsf, we resample images to display larger or smaller on screen than their native resolution using a linear filter. This works very well for satellite imagery for example. Nonetheless, a nearest neighbour filter would be more appropriate in your case, but SurfaceImage doesn't expose an option for changing this behaviour. We started working on this as part of #267. Could you try with the code in the branch `feature/surface-image-resampling-mode` and the new property below?

```javascript
var surfaceImage = new WorldWind.SurfaceImage(...);
surfaceImage.resamplingMode = WorldWind.FILTER_NEAREST;
```

Let us know if this produces the expected result for your use case. Please note that the public interface for this new option isn't definitive yet. Thank you.

**Comment by devsf** [comment]
Hi @AkeluX , thanks for the response!
We tested the fix on Windows/Linux and Chrome/Firefox.

It works on Linux using both Chrome and Firefox: ![istantanea_2017-11-02_10-22-03](https://user-images.githubusercontent.com/8003010/32320040-bd48e41e-bfbc-11e7-9aeb-4fb2b7e9c7fb.png), while there's still the blur effect on Windows (both on Firefox and Chrome).

I don't know, maybe it's a problem out of your scope or maybe you can fix the issue in some way.

Please, let me know! Thanks! :)

**Comment by AkeluX** [comment]
Windows is known to have limitations with WebGL. We'll investigate whether this can be solved or not. In the meantime, could you give me your Windows version and the version of the browsers as well? Thank you.

**Comment by devsf** [comment]
Sure!
Windows 10 Home (v1709, build 16299.19)
Chrome 62.0.3202.75 (64bit)
Firefox Developer Edition 57.0b13 (64bit)

**Comment by AkeluX** [comment]
The expected rendering is displayed by commenting out this line on Windows:
https://github.com/NASAWorldWind/WebWorldWind/blob/a3bbd4d42859f881d6258c8047830d9556757b42/src/render/Texture.js#L73

I haven't figured it all out yet and will keep digging. The good news is that there is no intrinsic limitation and we can improve this.

**Comment by AkeluX** [comment]
> The particular scheme for anisotropic texture filtering is implementation dependent.  Additionally, implementations are free to consider the current texture minification and magnification modes to control the specifics of the anisotropic filtering scheme used. https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_texture_filter_anisotropic.txt

It seems that Mac and Linux do consider the nearest neighbor magnification filter, but not Windows. Still in `feature/surface-image-resampling-mode`, I've pushed a change that enables this extension only if we have a linear magnification filter. It works for me on Windows.

@devsf, could you confirm that this solves your problem?

**Comment by devsf** [comment]
Hi @AkeluX ! Yes, it works! Please, let me know when the fix will be pushed into the develop branch! Thank you so much!
