### ISSUE TITLE
Transition assets off worldwindserver.net

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WebWorldWind#246]
Closes NASAWorldWind/NASAWorldWind.github.io#112

**Comment by zglueck** [comment]
The examples [SimplestExample](https://github.com/NASAWorldWind/WebWorldWind/blob/develop/examples/SimplestExample.html) and [Standalone](https://github.com/NASAWorldWind/WebWorldWind/blob/develop/examples/Standalone.html) reference worldwindserver.net.

SimplestEample is attempting to downloading the minified library.

Standalone references worldwindserver.net as the location to access the data for the example (as a download).

**Comment by zglueck** [comment]
The [BMNGRestLayer](https://github.com/NASAWorldWind/WebWorldWind/blob/develop/src/layer/BMNGRestLayer.js#L75) includes a fallback to worldwindserver.net for Blue Marble imagery.
