### ISSUE TITLE
Broken jsdoc task with Node 8.8.0+

### ISSUE THREAD

**Issue by AkeluX** [NASAWorldWind/WebWorldWind#274]
### Description
The build process fails with the following log.
```
Running "jsdoc:dist" (jsdoc) task
>> fs.js:1910
>> binding.copyFile(src, dest, flags);
>> ^
>> 
>> Error: EPERM: operation not permitted, copyfile 'C:\Users\...\WebWorldWind\node_modules\jsdoc\templates\default\static\fonts \OpenSans-Bold-webfont.eot' -> 'C:\Users\...\WebWorldWind\api-doc\fonts'
>> at Object.fs.copyFileSync (fs.js:1910:11)
>> at C:\Users\...\WebWorldWind\node_modul es\jsdoc\templates\default\publish.js:47 1:12
>> at Array.forEach (<anonymous>)
>> at Object.exports.publish (C:\Users\...\WebWorldWind\node_modu les\jsdoc\templates\default\publish.js:4 68:17)
>> at Object.module.exports.cli.generateDocs (C:\Users\...\WebWorldWind\node_modu les\jsdoc\cli.js:430:39)
>> at Object.module.exports.cli.processParseRe sults (C:\Users\...\WebWorldWind\node_modu les\jsdoc\cli.js:383:20)
>> at module.exports.cli.main (C:\Users\...\WebWorldWind\node_modu les\jsdoc\cli.js:227:14)
>> at Object.module.exports.cli.runCommand (C:\Users\...\WebWorldWind\node_modu les\jsdoc\cli.js:180:5)
>> at C:\Users\...\WebWorldWind\node_modul es\jsdoc\jsdoc.js:103:9
>> at Object.<anonymous> (C:\Users\...\WebWorldWind\node_modu les\jsdoc\jsdoc.js:104:3)
>> at Module._compile (module.js:635:30)
>> at Object.Module._extensions..js (module.js:646:10)
>> at Module.load (module.js:554:32)
>> at tryModuleLoad (module.js:497:12)
>> at Function.Module._load (module.js:489:3)
>> at Function.Module.runMain (module.js:676:10)
Warning: jsdoc terminated with a non-zero exit code Use --force to continue.

Aborted due to warnings.

npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! @nasaworldwind/worldwind@0.0.1 build: `grunt`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the @nasaworldwind/worldwind@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.
```

### Steps to Reproduce
1. Install Node 8.9.0
2. npm install
3. npm run build

**Expected behavior:**
Build process succeeds.

**Actual behavior:**
Build process fails.

**Reproduces how often:**
This was reported by two users, but I can't reproduce it personally.

### Operating System and Version
Windows 7 / Node 8.9.0 / NPM 5.5.1
MacOS 10.12.6 / Node 8.8.0 / NPM 5.4.2

**Comment by AkeluX** [comment]
It works fine with Node 6.9.2 and 6.11.1.

See https://forum.worldwindcentral.com/forum/web-world-wind/web-world-wind-help/157997-developer-branch-build-problem

**Comment by Beak-man** [comment]
It's working in 6.9.5 as well. I'll update node in my laptop and test.

**Comment by AkeluX** [comment]
@Beak-man, just a thought. Node Version Manager (nvm) is quite useful for using multiple versions of node on a single machine.

**Comment by Beak-man** [comment]
Sadly nvm is not supported on Windows. There's now an 'nvm-windows' package (developed by a different team) that I've yet to test.

**Comment by Beak-man** [comment]
I updated Node's runtime to 8.9.1 and was able to reproduce the reported issue in the system's terminal. Furthermore, trying to build WebWW from WebStorm's terminal locks up WebStorm. WebStorm stays locked up even after a system restart, which is really concerning. This with Windows 10.

**Comment by Beak-man** [comment]
The problem seems to arise from outdated npm packages that produce conflicts with the newer versions of Node's runtime. In the branch 'fix/Node_8_9_1_build' I updated our package.json file via `npm update`. I had to manually delete the 'node_modules' folder afterwards, since it was giving me [this error](https://github.com/Ninja-Squad/quizz/issues/4). Then I pushed to the branch, so anybody can test with the new package.json without deleting the folder.

- I updated to the last version of Node (via the installer in Windows and `brew upgrade node` with homebrew in Mac OS).
- After updating the runtime, I updated npm as well: `npm install npm@latest -g`.
- At the aforementioned branch, doing an 'npm install'.
- 'npm run build' works now. This has been tested in Windows 10 and Mac OS X Sierra.

Any help testing in other environments will be appreciated.

**Comment by markpet49** [comment]
@Beak-man On the develop branch, I was able to reproduce the bug with a somewhat different message on Ubuntu 16.04 than originally reported. The problem no longer occurs with your changes on the fix/Node_8_9_1_build branch, so I think you're good to go.
