### ISSUE TITLE
Review server and examples configuration

### ISSUE THREAD

**Issue by zglueck** [NASAWorldWind/WebWorldWind#296]
This task will evaluate several small configuration properties of the files.worldwind server and the examples.

- [x] Investigate NGINX for caching and other performance enhancements
- [x] Review the examples for unnecessary dependency downloads
- [x] Configure a shorter cache period for the the artifactory/apps root
- [x] Investigate the inclusion of the LICENSE and README files in different folders of the npm tarball
- [x] Investigate use of server compression for assets

**Comment by zglueck** [comment]
Tests against an NGINX caching service were inconclusive with respect to page loading times. In most cases the NGINX hosted files were provided with slightly faster download times (0%-70% faster) but the average difference was negligible in terms of the UI experience of a user. For these tests, client side caching was disabled; however, in the deployed configuration, the client side caching mechanism would show significant page loading improvement (as expected).

**Comment by zglueck** [comment]
A reviewed of the example dependencies indicated all were required for examples operation. Substitution of the latest versions of the libraries (jquery, bootstrap, and requirejs) had a minimal download speed improvement. Removing the bootstrap glyphicon for the magnifying glass on the search form and replacing with the unicode equivalent (`&#128269`) does prevent the downloading of the entire glyphicon library (18kb).

The graphic below shows a representative download timeline for the BasicExample. On the left is the current BasicExample.html and the right the updated version.

![screen shot 2017-11-14 at 10 08 45 am](https://user-images.githubusercontent.com/4935133/32790417-027b3940-c924-11e7-9609-b65e96ae2695.png)

**Comment by zglueck** [comment]
A `Cache-Control` header is set for the `/artifactory/web` URI root on the files.worldwind.arc.nasa.gov server. The max-age is set to the maximum value as the assets on this URI will not change.

A `Cache-Control` header is set for the `/artifactory/apps/web` URI root on the files.worldwind.arc.nasa.gov server. The max-age is set for five minutes as this asset will update with changes to the develop branch.

**Comment by pdavidc** [comment]
@zglueck Are you referring to this Google Developers guide?
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching

**Comment by zglueck** [comment]
@pdavidc yes, that is the one, I was working through the flow diagram under the section
> Defining optimal Cache-Control policy

**Comment by zglueck** [comment]
DEFLATE compression has been added on the files server. Client's providing an `Accept-Encoding: gzip` will be provided with a zipped version of the asset. Zipping reduces the `worldwind.min.js` file to 224kb and download time by approximately 300ms.
