### ISSUE TITLE
Add a loading progress indicator to GeoTiffExample

### ISSUE THREAD

**Issue by markpet49** [NASAWorldWind/WebWorldWind#299]
### Description

While loading the GeoTiffExample the browser appears to hang while the GeoTiff is loaded. The delay is long enough that I considered killing the process.

### Steps to Reproduce

Run the example.

**Expected behavior:** Some sort of feedback that activity is occurring.

**Actual behavior:** Browser was unresponsive for several seconds.

**Reproduces how often:** Any time the image is not in the cache. I didn't test the behaviour when the image is cached.

### Operating System and Version

Ubuntu 16.04/Chrome 61

**Comment by pdavidc** [comment]
Relates to #327

**Comment by claudiaifrim** [comment]
See pull request https://github.com/NASAWorldWind/WebWorldWind/issues/299
