### ISSUE TITLE
Downloading standalone archive certificate error

### ISSUE THREAD

**Issue by markpet49** [NASAWorldWind/WebWorldWind#300]
### Description

Downloading data as specified in examples/Standalone.html requires bypassing a certificate error.
https://worldwind32.arc.nasa.gov/WebWorldWind-StandaloneData.tar.gz

### Operating System and Version

Ubuntu 16.04/Chrome 61

**Comment by Beak-man** [comment]
As of now, I could download the file and unpack it without issues. (Windows 10/Chrome 62).

**Comment by markpet49** [comment]
Worldwind32 now has a valid certificate.
