### ISSUE TITLE
Small screen: Annotations example canvas overlaps the view controls 

### ISSUE THREAD

**Issue by markpet49** [NASAWorldWind/WebWorldWind#301]
### Description

The WW canvas in the Annotations example overlaps with the controls on the left side. If you zoom in on the globe, the problem is apparent. 

### Operating System and Version

Ubuntu 16.04/Chrome 61

**Comment by zglueck** [comment]
Also observed in Android 7
![screen shot 2017-11-15 at 9 27 13 am](https://user-images.githubusercontent.com/4935133/32844149-4447a9da-c9e7-11e7-983d-d67261e8023d.png)

**Comment by pdavidc** [comment]
This appears to be common to small screens.
