### ISSUE TITLE
GeoJSON example usability and data inconsistencies

### ISSUE THREAD

**Issue by Beak-man** [NASAWorldWind/WebWorldWind#304]
Child of #557

### Description
Data acquisition inconsistencies:

- GeoJSON resources take a while to load without any progress indicator. 
- GeoJSON files are being loaded from worldwindserver.net, this in spite of the code pointing towards "https://worldwind.arc.nasa.gov/web/examples/data/geojson-data/" [(line 86)](https://github.com/NASAWorldWind/WebWorldWind/blob/release/0.9.0/examples/GeoJSON.js#L86).

Data contents inconsistencies:
- USA 3857-linked looks very misaligned compared to the other USA boundaries files (it is offset to the north).

Data display inconsistencies:
- Some assets seem to be displayed twice (Italy and Romania's borders, a LineString between Bucharest and Constata with white points at its ends, the Danube river). The duplicates don't have layer controls. This makes the visualization difficult when switching on and off from the Layer Manager the following assets: 
  * Polygon (Romania's borders)
  * MultiPolygon (Italy's borders)
  * MultiPoint (a point over Bucharest and another one 5000 m over Constata)
  * LineString (a line between the two previous cities)
  * MultiLineString (the Danube river).
- It's very difficult to find out where the Point is being displayed. (Iasi city in Romania).

Console warning:
- When "World Main Cities" layer is first displayed, warning described in #302 is displayed in console.

### Operating System and Version

Windows 10, Chrome 62.0.

**Comment by Beak-man** [comment]
@markpet49 pointed out the difficulty of using the GeoJSON example in #217

**Comment by balhar-jakub** [comment]
Confirm the issues

**Operating System and Version**
Windows 10 / Edge 40

**Comment by zglueck** [comment]
When all GeoJSON layers are disabled in the layer manager the following shapes still appear:

![screen shot 2017-11-16 at 2 45 06 pm](https://user-images.githubusercontent.com/4935133/32957682-0f901b54-cb82-11e7-8617-6dc4986d71d2.png)

**Comment by claudiaifrim** [comment]
Confirmed for Linux Mint 18.2 Cinnamon, Firefox 57.0.

**Comment by pdavidc** [comment]
@Beak-man Would you please verify whether or not resources are still loading from worldwindserver.net?

**Comment by Beak-man** [comment]
@pdavidc They're loading from worldwind.arc.nasa.gov now.

**Comment by AkeluX** [comment]
Yes, almost all points raised in this issue are still valid. We'll address some of these with @claudiaifrim.
