### ISSUE TITLE
Win10+Chrome: Measurements example error

### ISSUE THREAD

**Issue by Beak-man** [NASAWorldWind/WebWorldWind#307]
### Description

Measurements example is producing the following error in the console when the 'calc' button is clicked:
`Uncaught TypeError: Cannot read property 'GluTesselator' of undefined
    at l.tessellatePolygon (worldwind.min.js:86)
    at l.computeProjectedAreaGeometry (worldwind.min.js:86)
    at l.getArea (worldwind.min.js:86)
    at HTMLButtonElement.doCalc (Measurements.js:61)`

### Steps to Reproduce

Load the example and press 'Calc' button.

**Expected behavior:**
I remember seeing this example working before. It correctly produced the polygon's measurements.

**Actual behavior:**
No quantities are shown in the left sidebar. The aforementioned error is shown in the console.

**Reproduces how often:**
Seems to happen every time.
### Operating System and Version
Windows 10, Chrome 62.0.

**Comment by claudiaifrim** [comment]
Confirmed for Linux Mint 18.2 Cinnamon, Firefox 57.0.

I receive the error : "TypeError: window.libtess is undefined"

**Comment by pdavidc** [comment]
Measurements works correctly running from WebStorm on macOS, but exhibits the errors reported above running online.

**Comment by AkeluX** [comment]
This happens when using the bundled library (minified or not), which is very easy to test thanks to the WorldWindShim :)
