### ISSUE TITLE
Polygons example image location is incorrect

### ISSUE THREAD

**Issue by Beak-man** [NASAWorldWind/WebWorldWind#308]
### Description
One of the polygons (the one located over Texas, Oklahoma and Arkansas) isn't loading its corresponding texture. Console produces the following error:
`GET http://127.0.0.1:8080/images/400x230-splash-nww.png 404 (Not Found)` (assuming execution from a local web server).

The same texture is correctly loaded elsewhere in the same example. This is because the correct address is:
`/examples/data/400x230-splash-nww.png`

### Operating System and Version

Windows 10, Chrome 62.0.

**Comment by balhar-jakub** [comment]
Confirm the issue

**Operating System and Version**
Windows 10 / Edge 40

**Comment by claudiaifrim** [comment]
Confirmed for Linux Mint 18.2 Cinnamon, Firefox 57.0

**Comment by markpet49** [comment]
When addressed, make sure #332 is fixed as well.
