### ISSUE TITLE
GeoTiffExample example console message

### ISSUE THREAD

**Issue by markpet49** [NASAWorldWind/WebWorldWind#309]
### Description

Log error when loading: Ignored GeoTiff key: 3076

### Operating System and Version

Ubuntu 16.04/Chrome 61

**Comment by balhar-jakub** [comment]
Confirm the issue

**Operating System and Version**
Windows 10 / Edge 40

**Comment by claudiaifrim** [comment]
Confirmed for Linux Mint 18.2 Cinnamon, Firefox 57.0

**Comment by claudiaifrim** [comment]
Fixed. See https://github.com/NASAWorldWind/WebWorldWind/pull/447

The implementation of the GeoTiff is a prototype and does not include all the metadata from GeoTiff specification, but we can add any new geokey that we need easily.
