### ISSUE TITLE
KmlExample log error

### ISSUE THREAD

**Issue by markpet49** [NASAWorldWind/WebWorldWind#310]
### Description

worldwind.min.js:84 StyleResolver.handleRemoteStyle: Style was null.

### Operating System and Version

Ubuntu 16.04/Chrome 61

**Comment by balhar-jakub** [comment]
Warning is issued in console that the remote style is null.

**Operating System and Version**
Windows 10 / Edge 40

**Comment by claudiaifrim** [comment]
Confirmed for Linux Mint 18.2 Cinnamon, Firefox 57.0
