### ISSUE TITLE
Measurements example console error

### ISSUE THREAD

**Issue by markpet49** [NASAWorldWind/WebWorldWind#313]
### Description

Pressing the Calc button in the Measurements exmaple results in: Uncaught TypeError: Cannot read property 'GluTesselator' of undefined. The button does not appear to function.

### Operating System and Version

Ubuntu 16.04/Chrome 61

**Comment by balhar-jakub** [comment]
Confirm the issue.

**Operating System and Version**
Windows 10/Edge 40

**Comment by balhar-jakub** [comment]
It is also duplicate of #307

**Comment by markpet49** [comment]
I missed the fact that Miguel had created an issue for this a few hours earlier.

**Comment by claudiaifrim** [comment]
Confirmed for Linux Mint 18.2 Cinnamon, Firefox 57.0.

I receive the error : "TypeError: window.libtess is undefined"
