### ISSUE TITLE
DigitalGlobe - Expired access key

### ISSUE THREAD

**Issue by balhar-jakub** [NASAWorldWind/WebWorldWind#314]
### Description

When loading the DigitalGlobe.html example the Mapbox API for the DigitalGlobe returns 401 HTTP Status

### Operating System and Version

WIndows 10 / Edge 40

**Comment by claudiaifrim** [comment]
Confirmed for Linux Mint 18.2 Cinnamon, Firefox 57.0.

**Comment by markpet49** [comment]
The access key is expired, either update the key or remove the example.
