### ISSUE TITLE
BlueMarbleTimeSeries imagery does not display

### ISSUE THREAD

**Issue by balhar-jakub** [NASAWorldWind/WebWorldWind#316]
### Description

Image retrieval failed: 
URL:
file:///C:/Users/Jakub%20Balhar/Projects/EOAPPS/WebWorldWind/Release%200.9.0/WebWorldWind-Distribution-0.9.0-RC2/examples/undefinedBlueMarble-200412/0/2/2_6.jpg
or URL:
http://localhost:63343/WebWorldWind-Distribution-0.9.0-RC2/examples/undefinedBlueMarble-200412/0/3/3_2.jpg

### Operating System and Version

Windows 10 / Edge 40

**Comment by Beak-man** [comment]
Confirmed in Windows 10/Chrome 62

**Comment by claudiaifrim** [comment]
Confirmed for Linux Mint 18.2 Cinnamon, Firefox 57.0.

**Comment by claudiaifrim** [comment]
GET http://dev.www-rc2.localhost/examples/undefinedBlueMarble-200412/0/2/2_6.jpg 404 (Not Found)
GET http://dev.www-rc2.localhost/examples/undefinedBlueMarble-200412/0/3/3_0.jpg 404 (Not Found)
GET http://dev.www-rc2.localhost/examples/undefinedBlueMarble-200412/0/3/3_1.jpg 404 (Not Found)

**Comment by eirizarry** [comment]
Confirmed in iOS 10.3.3/Safari 11.0

**Comment by pdavidc** [comment]
BlueMarbleRESTLayer's constructor was recently refactored, but this example was not updated to reflect that change.
