### ISSUE TITLE
Wkt - Custom WKT parsing doesn't work

### ISSUE THREAD

**Issue by balhar-jakub** [NASAWorldWind/WebWorldWind#317]
### Description

When trying to parse the custom WKT String there is an error in the Console. 
Object doesn't support this action when trying to add custom WKT shape

### Operating System and Version

Windows 10 / Edge 40

**Comment by Beak-man** [comment]
Confirmed in Windows 10/Chrome 62

**Comment by zglueck** [comment]
Getting the `WorldWind.WktParser is not a constructor` error log message in Android.

**Comment by claudiaifrim** [comment]
Confirmed for Linux Mint 18.2 Cinnamon, Firefox 57.0
