### ISSUE TITLE
Wkt - Green triangles are never removed as if they weren't in any of the three layers.

### ISSUE THREAD

**Issue by balhar-jakub** [NASAWorldWind/WebWorldWind#318]
### Description

The triangles with the green interior aren't removed by removing any of the Wkt Layers. 

### Operating System and Version

Windows 10 / Edge 40

**Comment by claudiaifrim** [comment]
Confirmed for Linux Mint 18.2 Cinnamon, Firefox 57.0

**Comment by markpet49** [comment]
Merged with #370
