### ISSUE TITLE
Collada example layer manager missing

### ISSUE THREAD

**Issue by zglueck** [NASAWorldWind/WebWorldWind#325]
### Description

The layer manager is not appearing.

### Steps to Reproduce

1. Load the Collada Example

**Expected behavior:** [What you expect to happen]

The layer manager to appear below the projection selection dropdown menu

**Actual behavior:** [What actually happens]

No layer manager

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Operating System and Version

Android 7.1.1/Chrome 62

![screen shot 2017-11-15 at 10 07 56 am](https://user-images.githubusercontent.com/4935133/32846689-893bbf80-c9ed-11e7-8edd-84b2c2c04ba3.png)

**Comment by Beak-man** [comment]
Confirmed in Windows 10/Chrome 62

**Comment by claudiaifrim** [comment]
Confirmed for Linux Mint 18.2 Cinnamon, Firefox 57.0.
