### ISSUE TITLE
Deep Picking example references wrong line in comments

### ISSUE THREAD

**Issue by zglueck** [NASAWorldWind/WebWorldWind#326]
### Description

The comments note to look at line 117; however, it is now line 116

### Steps to Reproduce

1. Open file

**Expected behavior:** [What you expect to happen]

Note line 116 instead of 117

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

**Comment by Beak-man** [comment]
As of now, the line that refers to deep picking is 124.
