### ISSUE TITLE
NDVIViewer example console warning

### ISSUE THREAD

**Issue by markpet49** [NASAWorldWind/WebWorldWind#331]
### Description

When run, the following console warning is given for the NDVIViewer example.

[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. 

### Operating System and Version

Ubuntu 16.04/Chrome 61

**Comment by claudiaifrim** [comment]
Confirmed for Linux Mint 18.2 Cinnamon, Firefox 57.0

**Comment by pdavidc** [comment]
Closing in favor of #328, which captures the potential side effect of performing a blocking XMLHttpRequest on Android.
