### ISSUE TITLE
Polygons example console errors

### ISSUE THREAD

**Issue by markpet49** [NASAWorldWind/WebWorldWind#332]
### Description

When running the Polygons example the following console errors are displayed.

worldwind.min.js:84 WorldWindow.drawOrderedRenderables: Error while rendering an ordered renderable.
Matrix.multiplyByTextureTransform: The specified texture is null or undefined.
log @ worldwind.min.js:84
worldwind.min.js:84 Matrix.multiplyByTextureTransform: The specified texture is null or undefined.	

### Operating System and Version

Ubuntu 16.04/Chrome 61

**Comment by claudiaifrim** [comment]
Confirmed for Linux Mint 18.2 Cinnamon, Firefox 57.0

**Comment by markpet49** [comment]
The fix for #308 should fix this as well.
