### ISSUE TITLE
ScreenText example picking not working

### ISSUE THREAD

**Issue by markpet49** [NASAWorldWind/WebWorldWind#333]
### Description

In the ScreenText example, picking only works on the center text and not on the text in the corners. In addition, when the center text is picked the following error is displayed in the console:

WARNING: there is no texture bound to the unit 0

### Operating System and Version

Ubuntu 16.04/Chrome 61

**Comment by claudiaifrim** [comment]
On Linux Mint 18.2 Cinnamon, Firefox 57.0 picking do not work at all.

**Comment by pdavidc** [comment]
@AkeluX I have time to investigate this today.
