### ISSUE TITLE
Starfield example - Simulate doesn't work on flat projections. 

### ISSUE THREAD

**Issue by markpet49** [NASAWorldWind/WebWorldWind#334]
### Description

In the StarField example, the simulate checkbox does nothing in flat projections. Possibly related: Issue #319.

### Operating System and Version

Ubuntu 16.04/Chrome 61

**Comment by Beak-man** [comment]
Also observed in Windows 10/Chrome

**Comment by claudiaifrim** [comment]
Also observed in  Linux Mint 18.2 Cinnamon, Firefox 57.0

**Comment by pdavidc** [comment]
The underlying issue is the need for AtmosphereLayer support in 2D mode. Closing this issue in favor of #319.
