### ISSUE TITLE
SentinelWMTS app/WMTS example: Unnecessary console message

### ISSUE THREAD

**Issue by markpet49** [NASAWorldWind/WebWorldWind#337]
### Description

When running the WMTS example and the SentinelWMTS app, the following message is displayed in the console:
WmtsLayer.formLayerConfiguration: No default style available. 	A style will not be specified in tile requests.

### Operating System and Version

Ubuntu 16.04/Chrome 61

**Comment by claudiaifrim** [comment]
onfirmed for Linux Mint 18.2 Cinnamon, Firefox 57.0
