### ISSUE TITLE
BingMapsKey limited - not suitable for production

### ISSUE THREAD

**Issue by GabrielePrestifilippo** [NASAWorldWind/WebWorldWind#339]
### Description
On All the examples I get a warning stating:

> WARNING: You are using a limited use, non-production Bing Maps key.
> If you are developing an app or a web page this violates the Bing Terms of Use.
> Please visit https://www.microsoft.com/maps/choose-your-bing-maps-API.aspx to obtain your own key for your application.
> Specify that key to WorldWind by setting the WorldWind.BingMapsKey property to your key prior to creating any Bing Maps layers.

### Operating System and Version
Windows 10 (Version 1709)
Firefox 57.0 (64bit)

**Comment by claudiaifrim** [comment]
Confirmed on Linux Mint 18.2 Cinnamon tested on Firefox 57.0

**Comment by pdavidc** [comment]
This warning about the Bing Maps key is logged by design.
