### ISSUE TITLE
Examples and Apps protocol clean-up

### ISSUE THREAD

**Issue by GabrielePrestifilippo** [NASAWorldWind/WebWorldWind#340]
### Description

When running an example from a secure HTTPS resource, it's not possible to require an HTTP libraries, resulting in an error

### Steps to Reproduce

1. Open example: https://files.worldwind.arc.nasa.gov/artifactory/apps/web/examples/Measurements.html
2. Bootstrap CSS and JS not loading

### Operating System and Version

Windows 10 (Version 1709)
Firefox 57.0 (64bit)

**Comment by GabrielePrestifilippo** [comment]
On the WMTS example, it loads the tiles on `http://tiles.geoservice.dlr.de/service/wmts` but still gives a warning

**Comment by markpet49** [comment]
The apps and examples need to be cleaned up such that all included scripts and links explicitly use https.
