### ISSUE TITLE
SimplestExample is not displaying appropriate warning for Bing layers usage

### ISSUE THREAD

**Issue by Beak-man** [NASAWorldWind/WebWorldWind#342]
### Description

Unlike every other App or Example in the repository that uses Bing's layers, SimplestExample is not displaying the appropriate console warning indicating that the Bing maps key is of limited use and for non-production environments, in spite of showcasing the BingAerialWithLabelsLayer.

### Operating System and Version

Windows 10/Chrome 62

**Comment by pdavidc** [comment]
This is by design. Simplest Example uses the default logging level (Severe).
