### ISSUE TITLE
SurfaceImage reports terrain is null when close to the surface

### ISSUE THREAD

**Issue by strikerM** [NASAWorldWind/WebWorldWind#346]
### Description

SurfaceImage rendering throws when zooming in close to the surface (50m).
RenderableLayer.doRender: Error while rendering shape Surface Image. TypeError: t.terrain is null

### Steps to Reproduce

1. Open the SurfaceImage example
2. Zoom in close to the surface, around 50 meters altitude.

**Reproduces how often:** 100%

### Operating System and Version

macOS High Sierra 10.13.1 / Firefox 57.0 (64-bit)
iOS 11.1.1 / Safari 11.0

**Comment by pdavidc** [comment]
I'm seeing similar issues in macOS High Sierra 10.13.1 / Chrome.

This suggests SurfaceImage doesn't handle the case where the DrawContext's terrain property is null.
