### ISSUE TITLE
Release versions

### ISSUE THREAD

**Issue by letmaik** [NASAWorldWind/WebWorldWind#35]
It would be really good if Web World Wind would have a proper release procedure with versions, and those versions should then also be tagged as git tags and the release artifacts (js file) put into the corresponding github release.

**Comment by pdavidc** [comment]
I agree completely, and our team has plans to establish a WebWW release procedure in the near term. We'll be using the following Jira ticket internally to track our progress:
http://issues.worldwind.arc.nasa.gov/jira/browse/WWJS-59

**Comment by pdavidc** [comment]
We're working toward the first official release of Web World Wind now. Our goals for the first release include critical security improvements (HTTPS), critical performance improvements, and an improved navigation interface.

**Comment by pdavidc** [comment]
Superceded and resolved by #229

**Comment by pdavidc** [comment]
Closing in anticipation of release 0.9.0 (#229).
