### ISSUE TITLE
Subsurface apps frame rate

### ISSUE THREAD

**Issue by zglueck** [NASAWorldWind/WebWorldWind#355]
### Description

Frame time of greater than 400ms

### Steps to Reproduce

1. Open the Subsurface app

**Expected behavior:** [What you expect to happen]

Reasonable responsiveness

**Actual behavior:** [What actually happens]

Poor responsiveness

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Operating System and Version

Android 7.1.1/Chrome 62/Nexus 9
Android 8.0.0/Chrome 62/Nexus 5x

**Comment by pdavidc** [comment]
Duplicates #352
