### ISSUE TITLE
Offer unminified js file

### ISSUE THREAD

**Issue by letmaik** [NASAWorldWind/WebWorldWind#36]
For debugging it is helpful to have an unminified JS file of webworldwind. It would be convenient if that could be produced as part of the normal releases, maybe named webworldwind.src.js.  The `optimize: 'none'` option in the grunt file for the requirejs task seems to do the trick.

**Comment by pdavidc** [comment]
Thanks for the request. We'll be tracking this internally with the following Jira ticket:
http://issues.worldwind.arc.nasa.gov/jira/browse/WWJS-58

**Comment by emxsys** [comment]
Adding the following target to the requirejs task seems to work:
```javascript
        compileDebug: { 
                options: {
                    baseUrl: 'src',
                    name: '../tools/almond',
                    include: ['WorldWind'],
                    optimize: 'none',
                    out: 'worldwindlib.debug.js',
                    wrap: {
                        startFile: 'tools/wrap.start',
                        endFile: 'tools/wrap.end'
                    }
                }
            }
```

**Comment by AkeluX** [comment]
Should we name the normal file worldwind.js and the optimised file worldwind.min.js ? This is what most JavaScript libraries do.

We could also provide a source map for debugging using the minified version. What do you think?

**Comment by pdavidc** [comment]
Yann, Everything you mention here sounds good to me. Matching existing JavaScript library conventions wherever it makes sense is a good policy.

Additionally, it would be worth reviewing and modifying the WebWW Grunt file as necessary to ensure it's following standard Grunt and JS library conventions.
