### ISSUE TITLE
Win7+Internet Explorer: Sentinel WMTS console error

### ISSUE THREAD

**Issue by markpet49** [NASAWorldWind/WebWorldWind#362]
### Description

Running the SentinelWMTS app results in the following console error: 

SCRIPT5007: Unable to get property 'length' of undefined or null reference

### Operating System and Version

Windows 7/IE 11

**Comment by AkeluX** [comment]
The problem is actually in the OWS parser for WMTS. An incompatible shortcut was taken for listing the children of an XML node.
