### ISSUE TITLE
Elevations retrieval failed

### ISSUE THREAD

**Issue by claudiaifrim** [NASAWorldWind/WebWorldWind#368]
### Prerequisites

Open Shapefiles.html example

### Description

I receive the warning :

Elevations retrieval failed (): https://worldwind26.arc.nasa.gov/elev?service=WMS&request=GetMap&version=1.3.0&transparent=TRUE&layers=GEBCO,aster_v2,USGS-NED&styles=&format=application/bil16&width=256&height=256&crs=EPSG:4326&bbox=-45,45,0,90

### Steps to Reproduce

1. Open Shapefiles.html
2. Zoom in

**Reproduces how often:**
First time you open the example (after a clear cache for your browser)

### Operating System and Version

Linux Mint 18.2 Cinnamon, Firefox 57.0

**Comment by pdavidc** [comment]
@claudiaifrim This may have been an intermittent server-side issue. Can you still reproduce this?

**Comment by claudiaifrim** [comment]
Yes, it can be reproduced on other examples also (eg. apps Collada when you select the box from Model select input :Elevations retrieval failed (): https://worldwind26.arc.nasa.gov/elev?service=WMS&request=GetMap&version=1.3.0&transparent=TRUE&layers=GEBCO,aster_v2,USGS-NED&styles=&format=application/bil16&width=256&height=256&crs=EPSG:4326&bbox=-90,-135,-45,-90 )

**Comment by claudiaifrim** [comment]
On apps Explorer : Elevations retrieval failed (): https://worldwind26.arc.nasa.gov/elev?service=WMS&request=GetMap&version=1.3.0&transparent=TRUE&layers=GEBCO,aster_v2,USGS-NED&styles=&format=application/bil16&width=256&height=256&crs=EPSG:4326&bbox=-45,135,0,180

**Comment by claudiaifrim** [comment]
It seems that now I don't have this issue anymore.
This issue should be closed.
