### ISSUE TITLE
Standalone example not loading

### ISSUE THREAD

**Issue by claudiaifrim** [NASAWorldWind/WebWorldWind#369]
### Prerequisites

Open Standalone.html example.

### Description

The globe is not loaded.
See console errors/warnings:

The page was reloaded, because the character encoding declaration of the HTML document was not found when prescanning the first 1024 bytes of the file. The encoding declaration needs to be moved to be within the first 1024 bytes of the file.
Standalone.html:25
Elevations retrieval failed (Not Found): http://dev.www-rc2.localhost/examples/../standalonedata/Earth/DTED0/0/0/0_0.bil
worldwind.min.js:84:4758
Elevations retrieval failed (Not Found): http://dev.www-rc2.localhost/examples/../standalonedata/Earth/DTED0/0/0/0_1.bil
worldwind.min.js:84:4758
Elevations retrieval failed (Not Found): http://dev.www-rc2.localhost/examples/../standalonedata/Earth/DTED0/0/0/0_2.bil
worldwind.min.js:84:4758
Elevations retrieval failed (Not Found): http://dev.www-rc2.localhost/examples/../standalonedata/Earth/DTED0/0/1/1_0.bil
worldwind.min.js:84:4758
Elevations retrieval failed (Not Found): http://dev.www-rc2.localhost/examples/../standalonedata/Earth/DTED0/0/1/1_1.bil
worldwind.min.js:84:4758
Elevations retrieval failed (Not Found): http://dev.www-rc2.localhost/examples/../standalonedata/Earth/DTED0/0/1/1_2.bil
worldwind.min.js:84:4758
Elevations retrieval failed (Not Found): http://dev.www-rc2.localhost/examples/../standalonedata/Earth/DTED0/0/0/0_5.bil
worldwind.min.js:84:4758
Elevations retrieval failed (Not Found): http://dev.www-rc2.localhost/examples/../standalonedata/Earth/DTED0/0/1/1_5.bil
worldwind.min.js:84:4758
Elevations retrieval failed (Not Found): http://dev.www-rc2.localhost/examples/../standalonedata/Earth/DTED0/0/2/2_0.bil
worldwind.min.js:84:4758
Elevations retrieval failed (Not Found): http://dev.www-rc2.localhost/examples/../standalonedata/Earth/DTED0/0/2/2_1.bil
worldwind.min.js:84:4758
Elevations retrieval failed (Not Found): http://dev.www-rc2.localhost/examples/../standalonedata/Earth/DTED0/0/2/2_2.bil
worldwind.min.js:84:4758
Elevations retrieval failed (Not Found): http://dev.www-rc2.localhost/examples/../standalonedata/Earth/DTED0/0/1/1_3.bil
worldwind.min.js:84:4758
Elevations retrieval failed (Not Found): http://dev.www-rc2.localhost/examples/../standalonedata/Earth/DTED0/0/2/2_3.bil
worldwind.min.js:84:4758
Elevations retrieval failed (Not Found): http://dev.www-rc2.localhost/examples/../standalonedata/Earth/DTED0/0/1/1_4.bil
worldwind.min.js:84:4758
Elevations retrieval failed (Not Found): http://dev.www-rc2.localhost/examples/../standalonedata/Earth/DTED0/0/2/2_4.bil
worldwind.min.js:84:4758
Elevations retrieval failed (Not Found): http://dev.www-rc2.localhost/examples/../standalonedata/Earth/DTED0/0/2/2_5.bil
worldwind.min.js:84:4758
Image retrieval failed: http://dev.www-rc2.localhost/examples/../standalonedata/Earth/BlueMarble256/BlueMarble-200401/0/0/0_0.jpg
worldwind.min.js:84:4758
Image retrieval failed: http://dev.www-rc2.localhost/examples/../standalonedata/Earth/BlueMarble256/BlueMarble-200401/0/0/0_1.jpg
worldwind.min.js:84:4758
Image retrieval failed: http://dev.www-rc2.localhost/examples/../standalonedata/Earth/BlueMarble256/BlueMarble-200401/0/0/0_2.jpg
worldwind.min.js:84:4758
Image retrieval failed: http://dev.www-rc2.localhost/examples/../standalonedata/Earth/BlueMarble256/BlueMarble-200401/0/1/1_0.jpg
worldwind.min.js:84:4758
Image retrieval failed: http://dev.www-rc2.localhost/examples/../standalonedata/Earth/BlueMarble256/BlueMarble-200401/1/2/2_2.jpg
worldwind.min.js:84:4758
Image retrieval failed: http://dev.www-rc2.localhost/examples/../standalonedata/Earth/BlueMarble256/BlueMarble-200401/1/3/3_3.jpg
worldwind.min.js:84:4758
Image retrieval failed: http://dev.www-rc2.localhost/examples/../standalonedata/Earth/BlueMarble256/BlueMarble-200401/0/1/1_3.jpg
worldwind.min.js:84:4758
Image retrieval failed: http://dev.www-rc2.localhost/examples/../standalonedata/Earth/BlueMarble256/BlueMarble-200401/1/4/4_1.jpg
worldwind.min.js:84:4758
Image retrieval failed: http://dev.www-rc2.localhost/examples/../standalonedata/Earth/BlueMarble256/BlueMarble-200401/1/5/5_0.jpg
worldwind.min.js:84:4758
Image retrieval failed: http://dev.www-rc2.localhost/examples/../standalonedata/Earth/BlueMarble256/BlueMarble-200401/1/4/4_2.jpg
worldwind.min.js:84:4758
Image retrieval failed: http://dev.www-rc2.localhost/examples/../standalonedata/Earth/BlueMarble256/BlueMarble-200401/1/3/3_2.jpg
worldwind.min.js:84:4758
Image retrieval failed: http://dev.www-rc2.localhost/examples/../standalonedata/Earth/BlueMarble256/BlueMarble-200401/0/1/1_2.jpg
worldwind.min.js:84:4758
Image retrieval failed: http://dev.www-rc2.localhost/examples/../standalonedata/Earth/BlueMarble256/BlueMarble-200401/1/4/4_3.jpg
worldwind.min.js:84:4758
Image retrieval failed: http://dev.www-rc2.localhost/examples/../standalonedata/Earth/BlueMarble256/BlueMarble-200401/0/1/1_7.jpg
worldwind.min.js:84:4758
Image retrieval failed: http://dev.www-rc2.localhost/examples/../standalonedata/Earth/BlueMarble256/BlueMarble-200401/1/4/4_0.jpg
worldwind.min.js:84:4758
Image retrieval failed: http://dev.www-rc2.localhost/examples/../standalonedata/Earth/BlueMarble256/BlueMarble-200401/1/5/5_1.jpg
worldwind.min.js:84:4758
Image retrieval failed: http://dev.www-rc2.localhost/examples/../standalonedata/Earth/BlueMarble256/BlueMarble-200401/1/5/5_2.jpg
worldwind.min.js:84:4758
Image retrieval failed: http://dev.www-rc2.localhost/examples/../standalonedata/Earth/BlueMarble256/BlueMarble-200401/1/5/5_3.jpg
worldwind.min.js:84:4758
Image retrieval failed: http://dev.www-rc2.localhost/examples/../standalonedata/Earth/BlueMarble256/BlueMarble-200401/1/4/4_4.jpg
worldwind.min.js:84:4758
Image retrieval failed: http://dev.www-rc2.localhost/examples/../standalonedata/Earth/BlueMarble256/BlueMarble-200401/1/4/4_5.jpg

### Steps to Reproduce

1. Open Standalone.html example

**Reproduces how often:** 
100%

### Operating System and Version

Confirmed for Linux Mint 18.2 Cinnamon, Firefox 57.0

**Comment by pdavidc** [comment]
@claudiaifrim This example requires the standalone data archive. Did you follow the embedded instructions at the top of the HTML file?

**Comment by claudiaifrim** [comment]
works fine.

**Comment by SCKgithub** [comment]
I am facing the same problem when I try to publish my data which is in DTED format.
Can you please provide me the ways to render my Elevation data



log @ worldwind.min.js:99
14:57:29.359 worldwind.min.js:99 Elevations retrieval failed: http://localhost:8081/WebWorldWind-develop/examples/data/E074N34_elevation/0/0/0_0.bil. Unexpected content type null
log @ worldwind.min.js:99
14:57:29.360 worldwind.min.js:99 Elevations retrieval failed (Not Found): http://localhost:8081/WebWorldWind-develop/examples/data/E074N34_elevation/0/2/2_4.bil
log @ worldwind.min.js:99
14:57:29.360
