### ISSUE TITLE
Wkt example layer management issues

### ISSUE THREAD

**Issue by claudiaifrim** [NASAWorldWind/WebWorldWind#370]
### Prerequisites

Open Wkt.html example

### Description

We have two buttons named 'Wkt Shapes' that show/hide the shapes on the globe (have the same behavior).

### Steps to Reproduce

1. Open Wkt.html example

See image attached:

![firefox_screenshot_2017-11-20t17-41-06 363z](https://user-images.githubusercontent.com/4428527/33032909-543f3e50-ce2b-11e7-8a5b-ecc8ecd24758.png)

**Reproduces how often:**
100%

### Operating System and Version

Linux Mint 18.2 Cinnamon, Firefox 57.0

**Comment by pdavidc** [comment]
Nice catch. A recent change to Wkt's compeltionCallback behavior has resulted in the same layer being added twice. The example no longer needs to add the layer.

**Comment by markpet49** [comment]
Fix the issue called out in issue #318 in conjunction with this fix. 

"The triangles with the green interior aren't removed by removing any of the Wkt Layers."
