### ISSUE TITLE
Collada example and app - globe not loading

### ISSUE THREAD

**Issue by claudiaifrim** [NASAWorldWind/WebWorldWind#375]
Globe not loading in the Collada example and Collada app

See attached screenshot:

![firefox_screenshot_2017-11-21t08-36-40 564z](https://user-images.githubusercontent.com/4428527/33062484-1ef9d39a-cea8-11e7-9b17-64151d1ce25c.png)

Linux Mint 18.2 Cinnamon, Firefox 57.0

**Comment by pdavidc** [comment]
Appears to be related to map server issues at Ames. Needs further testing once the map servers are restored.

**Comment by claudiaifrim** [comment]
The globe it's loading ok.
This issue can be closed.
