### ISSUE TITLE
Error message on Explorer app example

### ISSUE THREAD

**Issue by claudiaifrim** [NASAWorldWind/WebWorldWind#376]
### Prerequisites

Open in browser apps/Explorer.html

### Description

When Open Street Map pressed in a few seconds appears a dialog with the message "Failed to retrieve WMS capabilities from http://neowms.sci.gsfc.nasa.gov/wms/wms."

See screenshot:

![error](https://user-images.githubusercontent.com/4428527/33063049-f4e455d8-cea9-11e7-8e79-2acfa13c85c5.png)

### Steps to Reproduce

1. Open in browser apps/Explorer.html
2. Press on Open Street Map
Observation : It happens only the first time the app is loading (clear the cache)

**Reproduces how often:** 
100%

### Operating System and Version

Linux Mint 18.2 Cinnamon, Firefox 57.0

**Comment by pdavidc** [comment]
Duplicates #351
