### ISSUE TITLE
SantinelWMTS app - Blue Marble not loading

### ISSUE THREAD

**Issue by claudiaifrim** [NASAWorldWind/WebWorldWind#377]
### Prerequisites

Open apps/SentinelWMTS.html in browser, deselect True Color and select Blue Marble & Landsat layer

### Description

 Blue Marble & Landsat layer not loading: 

Image retrieval failed: https://worldwind25.arc.nasa.gov/wms?service=WMS&request=GetMap&version=1.3.0&transparent=TRUE&layers=BlueMarble-200405,esat&styles=&format=image/jpeg&width=256&height=256&crs=EPSG:4326&bbox=48.69140625,2.4609375,48.8671875,2.63671875

### Steps to Reproduce

1. Open apps/SentinelWMTS.html in browser
2. deselect True Color layer
3. select Blue Marble & Landsat layer

- nothing loaded

**Reproduces how often:**

100%

### Operating System and Version
Linux Mint 18.2 Cinnamon, Firefox 57.0

**Comment by pdavidc** [comment]
Appears to be related to map server issues at Ames. Needs further testing once the map servers are restored.

**Comment by claudiaifrim** [comment]
Now it's loading.
This issue can be closed.
