### ISSUE TITLE
USGS slabs app console error

### ISSUE THREAD

**Issue by claudiaifrim** [NASAWorldWind/WebWorldWind#378]
### Prerequisites

Open in browser /apps/USGSSlabs.html and zoom in on the globe. You will receive in the console " ReferenceError: Logger is not defined" error.

### Steps to Reproduce

1. Open in browser /apps/USGSSlabs.html
2. Zoom in on the globe

**Reproduces how often:** 

100%

### Operating System and Version

Linux Mint 18.2 Cinnamon, Firefox 57.0

**Comment by zglueck** [comment]
Hello, @claudiaifrim do you still see this issue with the latest from the development branch?

**Comment by pdavidc** [comment]
@AkeluX @claudiaifrim We're unable to reproduce this issue, and we're wondering whether it's still reproducible in the develop branch on Linux Mint.

**Comment by claudiaifrim** [comment]
@zglueck I don't have this issue any more.
