### ISSUE TITLE
Provide https version of js bundle

### ISSUE THREAD

**Issue by letmaik** [NASAWorldWind/WebWorldWind#38]
Many websites use https nowadays and including an http resource is not possible then. I tried https://worldwindserver.net/webworldwind/worldwindlib.js but it says that the SSL certificate is expired. A strong motivation for making this happen is that github pages enforces https:// since recently and this means that building small demo pages for WebWorldWind is only possible by copying the js file, which some may find to be a hassle, considering the size of it.

**Comment by pdavidc** [comment]
We're looking into https support for WebWW across the board. Thanks for bringing up this specific aspect.

**Comment by pdavidc** [comment]
Superceded and resolved by #224

**Comment by pdavidc** [comment]
Closing in anticipation of the automated versioned js bundle available with #229.
