### ISSUE TITLE
macos - layers unresponsive

### ISSUE THREAD

**Issue by claudiaifrim** [NASAWorldWind/WebWorldWind#380]
### Prerequisites

Open Atmosphere example - select/deselect on compass/coordinates/view controls - no action for any of the layers

### Description

See screenshot:
<img width="1314" alt="screen shot 2017-11-21 at 15 05 23" src="https://user-images.githubusercontent.com/4428527/33074256-30fd4e84-cece-11e7-995e-ed176e8559da.png">

<img width="1294" alt="screen shot 2017-11-21 at 15 11 29" src="https://user-images.githubusercontent.com/4428527/33074294-4f7ad944-cece-11e7-8401-9505276532be.png">

### Steps to Reproduce

1. Open Atmosphere example
2. select compass
3. deselect compass

**Reproduces how often:**
100 %

### Operating System and Version

macOS High Sierra 10.13.1, Safari 11.0.1

**Comment by pdavidc** [comment]
@claudiaifrim The NASA servers have been intermittently down yesterday and today. Would you please determine whether the download errors still occur?

**Comment by claudiaifrim** [comment]
ok, I will test again on macos, safari

**Comment by claudiaifrim** [comment]
No errors now, but the compass, coordinates and view controls have the same behaviour as described initially (see issue description).

<img width="1253" alt="screen shot 2017-11-23 at 16 43 15" src="https://user-images.githubusercontent.com/4428527/33178274-4c9d62c2-d06e-11e7-95c1-f53faeccc551.png">

<img width="1242" alt="screen shot 2017-11-23 at 16 43 55" src="https://user-images.githubusercontent.com/4428527/33178278-51568b9a-d06e-11e7-9169-516682a6e0c5.png">

**Comment by AkeluX** [comment]
We believe this is related to the problem described in #379.
