### ISSUE TITLE
Failed to load resource: A server with the specified hostname could not be found.

### ISSUE THREAD

**Issue by claudiaifrim** [NASAWorldWind/WebWorldWind#381]
### Prerequisites
All the examples tested on macos - safari have this error:

[Error] Failed to load resource: A server with the specified hostname could not be found. (wms, line 0)

### Steps to Reproduce

1. Open any example in safari on macos

**Reproduces how often:**
100%

### Operating System and Version

macOS High Sierra 10.13.1, Safari 11.0.1

**Comment by pdavidc** [comment]
@claudiaifrim Is this substantially different from #379 and #380?

**Comment by claudiaifrim** [comment]
Now it's ok.
This issue can be closed.
