### ISSUE TITLE
"Is not a constructor" error with GeoJSONGeometry

### ISSUE THREAD

**Issue by mk29142** [NASAWorldWind/WebWorldWind#42]
I am trying to call the GeoJSONGeometry constructor. "new WorldWind.GeoJSONGeometry(...) " and i am not sure as to why it is giving me a "is not a constructor" error. Also when i try console.log(WorldWind.GeoJSONGeometry) it comes up as undefined.

**Comment by servetg** [comment]
Could you explain why do you need to call that constructor? What is the use case?
Are you trying to create a GeoJSONGeometry outside the GeoJSONParser?

**Comment by mk29142** [comment]
Yes, the file i have isn't a standard GeoJson file so i can't pass it in straight. so i am trying to convert part it to geojson using the geometry then passing it into the parser. In order to get things such as a point or trajectory to show on the globe.

**Comment by AkeluX** [comment]
Thank you for the additional information. We are working on making these classes "publicly" available from the WorldWind object.

**Comment by AkeluX** [comment]
It should work now. See pull request #45.

**Comment by pdavidc** [comment]
@mk29142 when you get the chance, would you please verify that this issue is resolved?

**Comment by mk29142** [comment]
It has been resolved, thank you
