### ISSUE TITLE
Shape editor feature enhancements

### ISSUE THREAD

**Issue by MrDulka** [NASAWorldWind/WebWorldWind#423]
Child of #511 

Hi, I started using the shape editor feature #366 and encountered a few things that could be possibly improved/added.

1. When I construct the ShapeEditorController now, it adds event listeners to world window that I have no way of turning off. It would be nice to have a possibility to turn off the shape editing. For example I would want to allow a user to edit a shape and then confirm it, thus finishing the shape editing.

2. The functionality now is that the shape editor allows control of every shape on the globe. It would be nice if there was a possibility to limit it, so I could somehow choose which shapes can be edited and which can't.

Thanks for consideration.

**Comment by AkeluX** [comment]
Thank you for your feedback. We are going in this direction. Please see also #427.

**Comment by AkeluX** [comment]
The version in #637 addresses these points.
