### ISSUE TITLE
GLSL Link Program Error on Internet Explorer 11

### ISSUE THREAD

**Issue by zglueck** [NASAWorldWind/WebWorldWind#46]
While attempting to load BasicExample.html WebWorldWind with an updated Internet Explorer 11, an error message to the console states: "linkProgram: Internal linker error". This error is followed by a number of null or undefined shader attribute errors.

This behavior has only been observed in IE11 on Windows 7 machines. A similar test with Windows 10 did not exhibit the error. Chrome and Firefox on the same Windows 7 machine do not have the same error.
![errorlist1](https://cloud.githubusercontent.com/assets/4935133/18013725/6549523c-6b8d-11e6-801c-4b4a972c4678.jpg)

**Comment by pdavidc** [comment]
Further investigation revealed that our use of the GLSL built-in variable gl_FrontFacing may be problematic on Win7/IE11 devices. We're continuing to investigate and will update this issue when we know more.

**Comment by zglueck** [comment]
There was an additional statement in one our fragment shaders that our Windows7/IE11 test environment was throwing the same error. I've removed the statement in commit 3b75352 

@gbchriste please try it out in your Win7/IE11 environment when you get a chance. It should resolve the issue you were seeing. If I here positively back from you I'll go ahead and close out this issue.

**Comment by gbchriste** [comment]
Will check it out tomorrow!

**Comment by AkeluX** [comment]
@zglueck do we have a confirmation that this is solved? Can we close the issue?

**Comment by zglueck** [comment]
@AkeluX all the testing we've conducted indicates this is solved, @gbchriste, who initially alerted us to the issue has run into some delays for testing in his specific environment, however, we did test on the a similar Win7/IE11 platform, so I think it would okay to go ahead and close it out. If we hear otherwise, we can just reopen.

**Comment by AkeluX** [comment]
Ok. Let's close it then.
