### ISSUE TITLE
Placemark label outline color does not work

### ISSUE THREAD

**Issue by sjpinizzotto** [NASAWorldWind/WebWorldWind#464]
Closes #173 

### Description

Created a placemark with TextAttributes.  Trying to set the outline color. (need black outline color for map backgrounds that are bright, and white outline for map backgrounds that are dark)

### Steps to Reproduce

1. Create a new PlacemarkAttributes object,
3. Create a new TextAttributes object, set outlineColor to some color to set the text outline color, 
4. Set the TextAttributes.color property to change color of text
5. assign the TextAttributes to the PlacemarkAttributes.labelAttributes
4. Add the placemark to the map.  

Extending your placemark example:

// Define the event listener to initialize Web WorldWind.
  function eventWindowLoaded() {
    // Create a WorldWindow for the canvas.
    var wwd = new WorldWind.WorldWindow("map");

    // Add some image layers to the WorldWindow's globe.
    wwd.addLayer(new WorldWind.BMNGOneImageLayer());
    wwd.addLayer(new WorldWind.BMNGLandsatLayer());

    // Add a compass, a coordinates display and some view controls to the WorldWindow.
    wwd.addLayer(new WorldWind.CompassLayer());
    wwd.addLayer(new WorldWind.CoordinatesDisplayLayer(wwd));
    wwd.addLayer(new WorldWind.ViewControlsLayer(wwd));

    var placemark, textAttributes,
      placemarkAttributes = new WorldWind.PlacemarkAttributes(null),
      highlightAttributes,
      placemarkLayer = new WorldWind.RenderableLayer("Placemarks"),
      latitude = 47.684444,
      longitude = -121.129722;

    // Set up the common placemark attributes.
    placemarkAttributes.imageScale = 1;
    placemarkAttributes.imageOffset = new WorldWind.Offset(
      WorldWind.OFFSET_FRACTION, 0.5,
      WorldWind.OFFSET_FRACTION, 0.5);
    placemarkAttributes.imageColor = WorldWind.Color.WHITE;

    // Create the custom image for the placemark.

    var canvas = document.createElement("canvas"),
      ctx2d = canvas.getContext("2d"),
      size = 64, c = size / 2 - 0.5, innerRadius = 5, outerRadius = 20;

    canvas.width = size;
    canvas.height = size;

    var gradient = ctx2d.createRadialGradient(c, c, innerRadius, c, c, outerRadius);
    gradient.addColorStop(0, 'rgb(255, 0, 0)');
    gradient.addColorStop(0.5, 'rgb(0, 255, 0)');
    gradient.addColorStop(1, 'rgb(255, 0, 0)');

    ctx2d.fillStyle = gradient;
    ctx2d.arc(c, c, outerRadius, 0, 2 * Math.PI, false);
    ctx2d.fill();

    // Create the placemark.
    placemark = new WorldWind.Placemark(new WorldWind.Position(latitude, longitude, 1e2), false, null);
    placemark.altitudeMode = WorldWind.RELATIVE_TO_GROUND;

    // Create the placemark attributes for the placemark.
    placemarkAttributes = new WorldWind.PlacemarkAttributes(placemarkAttributes);
    // Wrap the canvas created above in an ImageSource object to specify it as the placemark image source.
    placemarkAttributes.imageSource = new WorldWind.ImageSource(canvas);
    placemark.attributes = placemarkAttributes;

    // Create the label attributes
    textAttributes = new WorldWind.TextAttributes(null);
    textAttributes.color = new WorldWind.Color(1,0,0,1);
    textAttributes.outlineColor = new WorldWind.Color(0,1,0,1);
    placemarkAttributes.labelAttributes = textAttributes;

    // Create the highlight attributes for this placemark. Note that the normal attributes are specified as
    // the default highlight attributes so that all properties are identical except the image scale. You could
    // instead vary the color, image, or other property to control the highlight representation.
    highlightAttributes = new WorldWind.PlacemarkAttributes(placemarkAttributes);
    highlightAttributes.imageScale = 1.2;
    placemark.highlightAttributes = highlightAttributes;

    placemark.label = "Label Test";

    // Add the placemark to the layer.
    placemarkLayer.addRenderable(placemark);

    // Add the placemarks layer to the WorldWindow's layer list.
    wwd.addLayer(placemarkLayer);
  }

**Expected behavior:** [What you expect to happen]
I expect the color of the text to be the TextAttribute.color and the background outline of the text to be the TextAttribute.outlineColor.   In the example the text color is red, but the outline color is not green.

**Actual behavior:** [What actually happens]
It seems outline color is ignored, and it is always black.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Operating System and Version

[What operating system and version are you using?]
MacOS High Sierra 10.13.3 
Using Chrome

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by pdavidc** [comment]
Thanks @sjpinizzotto. We're actively working on text outline, and you may have caught us in the middle of that work.

We'll incorporate this in epic #173.

**Comment by pdavidc** [comment]
@sjpinizzotto Would you please clarify which version of WorldWind you're using? If not 0.9.0, then an abbreviated commit hash please.

**Comment by sjpinizzotto** [comment]
0.9.0

**Comment by pdavidc** [comment]
Thanks for clarifying. Release 0.9.0 does not provide support for Text outline color. You can use the latest code on develop to use the text outline capability now.
