### ISSUE TITLE
KML example on website is not working

### ISSUE THREAD

**Issue by sjpinizzotto** [NASAWorldWind/WebWorldWind#478]
**Note:** Any issue that does not include enough information to be reviewed in a timely manner may be closed at the
maintainer's discretion.

### Prerequisites

Please fulfill the following requirements before submitting an issue to this repository.

- Check the "Common Problems" page on the WorldWind website: https://worldwind.arc.nasa.gov/web/tutorials/common-problems/
- Check that your issue isn't already filed: https://github.com/NASAWorldWind/WebWorldWind/issues
- Check the WorldWind forum for common solutions: https://forum.worldwindcentral.com/forum/web-world-wind/web-world-wind-help

### Description
Was looking for your KML samples to check out web worldwind support, and I came across this. I was checking out how to get KML to work so I went to your site to see what you all did.  https://files.worldwind.arc.nasa.gov/artifactory/apps/web/examples/KmlExample.html
The KML sample does not appear to be working on your web site.   

Using Chrome (Version 64.0.3282.167)  I get: 
RenderableLayer.doRender: Error while rendering shape Renderable.
TypeError: Cannot read property 'toHexString' of undefined
log @ worldwind.min.js:85

Using Firefox (version 58.0.2) I get
StyleResolver.handleRemoteStyle: Style was null.
worldwind.min.js:85:4758
RenderableLayer.doRender: Error while rendering shape Renderable.
TypeError: e.outlineColor is undefined
worldwind.min.js:85:4721
StyleResolver.handleRemoteStyle: Style was null.
worldwind.min.js:85:4758
RenderableLayer.doRender: Error while rendering shape Renderable.
TypeError: e.outlineColor is undefined
worldwind.min.js:85:4721
StyleResolver.handleRemoteStyle: Style was null.
worldwind.min.js:85:4758
RenderableLayer.doRender: Error while rendering shape Renderable.
TypeError: e.outlineColor is undefined
https://files.worldwind.arc.nasa.gov/artifactory/apps/web/examples/KmlExample.html

### Steps to Reproduce

1 Navigate to https://files.worldwind.arc.nasa.gov/artifactory/apps/web/examples/KmlExample.html
2. Turn on and off checkboxes.  None of the checkboxes appear to do anything
3. Check error console.

**Expected behavior:** [What you expect to happen]
1. Expected to see kml polygons, points, lines etc.

**Actual behavior:** [What actually happens]
I do not see any KML on the map.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Operating System and Version
MacOS 10.13.3

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by pdavidc** [comment]
@sjpinizzotto I've attempted to reproduce this on MacOS 10.13.13 in the following browsers: Chrome, Safari, Firefox.

Is there anything else in the logs that might explain this discrepancy? Was it a transient issue?

**Comment by pdavidc** [comment]
@NASAWorldWind/nasa-developers @NASAWorldWind/esa-developers Is anyone able to reproduce this issue?

**Comment by AkeluX** [comment]
No, it's working fine for me, but same browsers and OS as you.

**Comment by emxsys** [comment]
@pdavidc Works for me in FireFox and Chrome on Windows 10.  It's essential to click on the links in the menu to zoom in on the various KML features.

**Comment by Beak-man** [comment]
Working for me in Firefox and Chrome on W10 as well.

**Comment by markpet49** [comment]
@pdavidc Linux - Chrome & Firefox do not currently display these symptoms. I wonder if the KML file failed to load for the user in this instance. I did notice some behavioural problems between the checkbox list and what was displayed, but I'll document those in a separate issue.

**Comment by markpet49** [comment]
@pdavidc FYI: I accidentally recreated this issue with older KML source as embodied in Miguel's ScreenCreditController branch. It would appear that newer changes to KML in the develop branch fixed the issue.

**Comment by pdavidc** [comment]
@sjpinizzotto We believe the issue has been fixed. Please try running the KML example again, making sure to clear your browser's cache if necessary.
