### ISSUE TITLE
Support HTMLCanvasElement object as argument of the WorldWindow constructor

### ISSUE THREAD

**Issue by AkeluX** [NASAWorldWind/WebWorldWind#479]
### Description

The proposition is to support giving an HTMLCanvasElement object to the constructor of WorldWindow as alternative to giving the ID of an existing canvas. This would greatly facilitate the integration of WebWorldWind with modern JavaScript frameworks like React, Angular and Polymer, which manages the DOM elements themselves.

**Expected behavior:**
a) Giving a string to WorldWindow uses getElementById for locating the actual canvas.
b) Giving an HTMLCanvasElement object to WorldWindow uses this canvas directly for the rendering.
c) Giving anything else to WorldWind fails.

**Comment by pdavidc** [comment]
@AkeluX This sounds like a reasonable addition to WorldWindow's constructor.
@markpet49 Do you have any questions or concerns?

**Comment by markpet49** [comment]
@pdavidc No concerns, it seems like a nice upgrade.

**Comment by AkeluX** [comment]
Ok. I'll add that next week then.
