### ISSUE TITLE
WCS GeoTiff response support

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WebWorldWind#483]
Closes #482

Establish support for WCS responses in GeoTiff format. Connect the existing GeoTiff reader with the existing ElevationModel retrieval logic, making any necessary adjustments.

**Comment by zglueck** [comment]
@pdavidc and @markpet49,  plumbing up the GeoTiff reader to the current WCS elevation wasn't too bad, but raised an oddity in the API and code flow between WcsElevationModel and GeoTiff.

The ElevationModel includes a generic XmlHttpRequest for retrieving bil data; however, the GeoTiffReader includes its own XmlHttpRequest and only offers two "public" methods for retrieving GeoTiff data (`readAsData` and `readAsImage`) which utilize its own implementation of the XmlHttpRequest.

The two XHR's modify internal state of their respective classes in different ways. I believe the best path forward is to refactor the GeoTiffReader to provide a "public" method for the parsing of data arrays (without the asynchronous request). The ElevationModel can then be refactored to appropriately branch on `image/tiff` content types.

The refactor of the GeoTiffReader to provide the public parsing method shouldn't require any significant technical deviation of the current implementation. I envision it mostly to formalize the data parsing in the facilitation of future maintenance.

I'll touch base with you a little later to discuss this path forward. I'd like to check I am on the right path.

**Comment by pdavidc** [comment]
@zglueck Thanks for touching base on this early your process.

You're right, WorldWind's format parsers must include a mechanism for reading directly from a generic buffer (what's the JavaScript equivalent of ByteBuffer)? It's critical that components like layers and elevation models are in control of network requests.
