### ISSUE TITLE
WCS compatible coverage construction

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WebWorldWind#486]
Child of #482

Modify the common TiledElevationCoverage implementation such that its construction can be easily used with an OGC Web Coverage Service, versions 1.0.0 and 2.0.1.

**Implementation Considerations**

WorldWind's components that interact with OGC services have historically required configuration at construction time, thereby putting the burden of the capabilities handshake somewhere in the application's domain. In my opinion, this has many drawbacks:
• Component configuration is awkward.
• Components are essentially immutable.
• Components are difficult to extend or compose.
• Applications have no reliable mechanism for responding to capabilities handshake failures that result from a poor network connection. 

Given the above, I think a better design is to put the burden of the capabilities handshake on each of WorldWind's OGC components. The component requires only essential information at construction time, and provides mutable properties (and/or methods) for configuration after construction. The capabilities information is retrieved lazily, as-needed, and the component configured appropriately if and when the capabilities response is received. I think the result will be a simple, easy to understand, and easy to extent first-class WorldWind component.

**Comment by zglueck** [comment]
The creation of the WebCoverageService manages version negotiation and parsing of WCS coverages. It provides a generic object which can be utilized by the refactored TiledElevationCoverage to easily and flexibly create elevation coverages based on WCS data providers.
