### ISSUE TITLE
Blank tiles appear after viewing large amounts of imagery

### ISSUE THREAD

**Issue by emxsys** [NASAWorldWind/WebWorldWind#497]
### Description

Blank tiles and poor performance experienced after viewing large amounts of imagery.  This problem is manifest in full screen desktop displays (landscape).

### Steps to Reproduce

This issue can be replicated in the BasicExample using the OSM layer by creating a large viewport.  

Change the BasicExample to use a full width and height canvas: change the `div.container` class to `container-fluid`, and change the `div#globe.col-sm-9` class to `col-sm-12`. Also change the canvas height from `auto` to `calc(100vh)`.
Example:
```
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <h4>Layers</h4>
            <div class="list-group" id="layerList">
            </div>
        </div>
        <div class="col-sm-12" id="globe">
            <canvas id="canvasOne" width="1000" height="1000" style="width: 100%; height: calc(100vh)">
                Your browser does not support HTML5 Canvas.
            </canvas>
        </div>
    </div>
</div>
```
1. Zoom in close to terrain
2. Tilt the view so horizon is in view
3. Using view controls, rotate the view continuously, expecting to see blank tiles within previously viewed content
4. Zoom out, expecting to see blank tiles in previously viewed content
5. Repeat 1 through 4. Over time the UI performance lags, possibly resulting in a lockup on the web page; and zoomed-out views fail to repopulate tiles.

**Expected behavior:** [What you expect to happen]
- No loss of performance
- Scene quickly and completely repopulated

**Actual behavior:** [What actually happens]
- Blank tiles appear that are either slow or fail to repopulate
- Globe navigation becomes sluggish
- Continuous network activity as tiles are re-downloaded 

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Operating System and Version
Windows 10

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Beak-man** [comment]
Confirmed in Chrome in Mac OS X 10.13 High Sierra

**Comment by Beak-man** [comment]
In Firefox Dev Edition 59.0b13 (again under Mac OS) the performance doesn't degrade nearly as much as with Chrome. I still see the white tiles that take a bit to repopulate, but the caching seems to work much better, from what I see in the network log.

**Comment by pdavidc** [comment]
@emxsys I'll be creating an epic to track the broader improvements we've been discussing, and this issue will become part of that epic.
