### ISSUE TITLE
OpenStreetMap layer not shown until mouse move

### ISSUE THREAD

**Issue by markpet49** [NASAWorldWind/WebWorldWind#503]
### Description

In the BasicExample, the Open Street Map layer does not display after clicking the layer button if you don't subsequently move the mouse. 

### Steps to Reproduce

1. Run BasicExample.
2. Click the Open Street Map button taking care not to move the mouse.

### Operating System and Version

Ubuntu 16.04/Chrome 64

**Comment by PJHogan** [comment]
Interesting, would seem to take the reflexes of a cat to catch! How the heck does a mouse move become a dependency to a layer toggle?

**Comment by Beak-man** [comment]
It seems to be a general bug throughout Apps and Examples. USGSSlabs shows this behavior as well.

**Comment by markpet49** [comment]
@PJHogan I'm theorizing that we are somehow missing a redraw call on the button click alone. Mouse movement can result in redraw calls in service of things like the Compass and Coordinates display.

**Comment by pdavidc** [comment]
Fix is in 855286b
