### ISSUE TITLE
CoordinatesDisplayLayer formatAltitude, convert meters to Km , Maybe it should be 10e2 

### ISSUE THREAD

**Issue by QingMings** [NASAWorldWind/WebWorldWind#54]
[https://github.com/NASAWorldWind/WebWorldWind/blob/master/src/layer/CoordinatesDisplayLayer.js](url);
on line 254

convert meters to km ,maybe  10e2, not 10e3 ,
![image](https://cloud.githubusercontent.com/assets/22107668/18825306/53cb39d2-83fa-11e6-9e83-b2f927610af0.png)

**Comment by AkeluX** [comment]
It's not 10e3. It's 1e3 (= 10e2) in the code and it seems fine to me. @QingMings, does that answer your question?

**Comment by AkeluX** [comment]
No answer. Let's consider it closed.
