### ISSUE TITLE
bug with rendering self-occult semi-transparent collada objects

### ISSUE THREAD

**Issue by strangerintheq** [NASAWorldWind/WebWorldWind#57]
![bug](https://cloud.githubusercontent.com/assets/5839866/18960885/e771fede-8673-11e6-9aa4-25a94156dd43.jpg)

**Comment by strikerM** [comment]
Can you share the model?

**Comment by strangerintheq** [comment]
i can't because some bug on GitHub, 

> We don’t support that file type.  Выбрать файлы Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.

i can send it directly to you by email or other service

**Comment by strangerintheq** [comment]
i forgot to tell that i modify alpha of material in runtime

**Comment by strikerM** [comment]
My email address is:
florin.draghici@qualteh.ro

**Comment by strikerM** [comment]
This is how the model looks when you make it transparent.
Here is an image from Blender with transparency.
![capture](https://cloud.githubusercontent.com/assets/14248863/18992037/b66f451a-8724-11e6-9f61-a21ca86c9059.PNG)

**Comment by strangerintheq** [comment]
thank you
