### ISSUE TITLE
speed-up

### ISSUE THREAD

**Issue by strangerintheq** [NASAWorldWind/WebWorldWind#59]
In my experiments with web world wind engine i found the way to minimize lags on slow machines while rotating the earth.

I do following:

By right mouse i apply following crutches: 
- limit throughput of loading tiles by TiledImageLayer and ElelevationModel
- disable Picking mode at all

And removing this crutches bu right mouse up.

I hope it will be helpful, if you want i can show my code =) good luck

**Comment by nicolasvila** [comment]
Hi, would you mind sharing your code?

**Comment by strangerintheq** [comment]
yes, if you really need it, i can extract some code from my sources, but i need some time for it.

**Comment by AkeluX** [comment]
Thank you for your suggestions. We are working on less application-dependent optimisations and will keep your ideas in mind and get back to you if needed.
