### ISSUE TITLE
when I using SurfacePolyline draw a path ,some points are independent ,Until I add a point far away from them.

### ISSUE THREAD

**Issue by QingMings** [NASAWorldWind/WebWorldWind#63]
see this 
  [Detailed description](https://forum.worldwindcentral.com/forum/web-world-wind/web-world-wind-help/17938-using-surfacepolyline-draw-a-path-some-points-are-independent)
.

**Comment by pdavidc** [comment]
@QingMings would you please test this fix?

**Comment by QingMings** [comment]
I just tested this fix,It's ok .Work fine .
Thanks . @pdavidc
