### ISSUE TITLE
OGC Web Coverage Service (WCS) interface

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WebWorldWind#639]
Child of #482 

Define an object model for interacting with an OGC Web Coverage Service (WCS). This model encapsulates the functionality of asynchronously discovering the service capabilities. Here are the use cases this functionality intends to support:

1. Given a service address, discover the coverages available.
2. Given a service address, construct WorldWind scene components for one or more coverages. 
3. Given a service address and a coverage name, construct a WorldWind scene component for that coverage.

**Comment by zglueck** [comment]
This work was completed in pr #652 and work on the WebCoverageService.
