### ISSUE TITLE
Z-Index of place mark has different results

### ISSUE THREAD

**Issue by dave-barrineau** [NASAWorldWind/WebWorldWind#64]
I submitted a question on the Forum but no replies and this looks to be a bug.  Here is the content of the forum post (http://forum.worldwindcentral.com/showthread.php?46248-Set-z-index-of-a-place-mark&p=125652#post125652)  EDIT: Link is no longer valid:

"The app I'm building can have overlapping place marks. When the user clicks on one that is behind another I want to bring the selected place mark to the top. (I have a sprite place mark that renders a border around an image of a place mark.) I've tried setting alwaysOnTop to true but that does not work. I also have tried setting the eyeDistance to a very small number (everywhere from 0 to 10) separate and in conjunction with the alwaysOnTop. I recompiled the Web World Wind library to not uglify (option passed to requirejs) and when setting eyeDistance and alwaysOnTop, it does work. However the uglified version does not."

** On the forum post I have two images of the uglified vs. non-uglified results.

**Comment by dave-barrineau** [comment]
What's the status of this issue?  My project is getting to a point where we're going to need this fixed.  Thanks.

**Comment by pdavidc** [comment]
@dave-barrineau The distinction about the RequireJS uglify option sounds suspicious. Have you tried using Placemark.alwaysOnTop with the 0.9.0 release library?

**Comment by dave-barrineau** [comment]
@pdavidc This appears to be fixed with 0.9.0 release (we just stepped up to this release a few weeks ago).  Therefore you can close this ticket.  If for any reason we happen to see it again I'll open a new ticket.  Thanks --Dave

**Comment by pdavidc** [comment]
Thanks, @dave-barrineau!
