### ISSUE TITLE
Bing logo is rendered multiple times per each Bing layer

### ISSUE THREAD

**Issue by Beak-man** [NASAWorldWind/WebWorldWind#687]
### Description
As an unintended effect of #661, each time a Bing layer is added to the globe, a new Bing logo is rendered as an overlay.

### Steps to Reproduce

1. Load a Bing layer (as in our examples, where Bing Aerial with Labels is shown on load).
2. Load another Bing layer.
3. See the Bing logo getting darker each time a Bing layer is added, and lightening each time a Bing layer is removed.

**Expected behavior:**
A single Bing logo is rendered no matter how many of Bing's layers are loaded into the globe.

**Actual behavior:**
Bing logos are rendered in top of another.

**Reproduces how often:**
100% of the time.

**Comment by pdavidc** [comment]
@Beak-man it’s good you caught this. Please fix this before continuing work on attribution positioning.

This is an indication that your testing is not thorough enough. Take the time to identify and try out all the ways in which a feature you’re working on might be used.

**Comment by Beak-man** [comment]
Will do, @pdavidc .
