### ISSUE TITLE
WMTS image layer (NSG profile)

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WebWorldWind#69]
Retrieval and display of imagery from an OGC Web Map Tile Services conforming to the NSG profile.

**Comment by zglueck** [comment]
The model of the WMTS GetCapabilities (WmtsCapabilities and WmtsLayerCapabilities) should match WWA.

Remaining Items:

- [ ] OGC WMTS sub folder creation and refactor
- [ ] WmtsLayerCapabilities -> WmtsLayer rename (pending current WmtsLayer future)
- [ ] plural property names (e.g. layer vs layers) in array based properties
- [ ] wmts.operationMetadata.getCapabilities shortcut utility
- [ ] wmts.getLayer(name) and wmts.getLayers() utility methods
- [ ] layer.wgs84BoundingBox addition of a getSector utility
- [ ] boundingBox assumes two values in the upper and lower corner elements
- [ ] layer.getLayerSupportedTileMatrixSets utility method
- [ ] layer.metadata support

**Comment by zglueck** [comment]
The refactored WMTS effort was merged to the develop branch in commit 9bd0d5d.

The three items not completed from the checklist above (Layer rename, plural property names, and boundingBox value storing) are captured in #89 for future work.

**Comment by zglueck** [comment]
Changed the TileMatrixSet TileMatrix sort key to be the scale denominator in b49f23f.

This is an artifact of how Web World Wind is currently matching the Level to the compatible TileMatrix index instead of matching the scale denominator.
