### ISSUE TITLE
SurfacePolygon: problem drawings antimeridian-crossing-polygons

### ISSUE THREAD

**Issue by devsf** [NASAWorldWind/WebWorldWind#70]
See [forum thread](http://forum.worldwindcentral.com/showthread.php?46259-SurfacePolygon-problem-drawings-across-dateline-polygons)

**Comment by AkeluX** [comment]
@strikerM is working on this. We have a new algorithm that is being integrated.

**Comment by devsf** [comment]
Hi! Any news on this?

**Comment by pdavidc** [comment]
We just merged a pull request from @strikerM that repairs this issue. Would you please re-run your tests with the latest code in the develop branch?

**Comment by devsf** [comment]
Hi! As you can see [here](https://www.dropbox.com/s/4jwhyaa5r6tb25o/Screenshot_2017-02-22_11-20-09.png?dl=0), the polygon is correctly rendered! Thanks!

**Comment by pdavidc** [comment]
@devsf, Thanks for verifying the fix.
