### ISSUE TITLE
Bing maps key not send in the URL

### ISSUE THREAD

**Issue by YvesE** [NASAWorldWind/WebWorldWind#72]
When creating a Bing Layer with a personal Bing maps key, the key is not send in the URL.
Then the response received is 
gov_nasa_worldwind_jsonp_0({"authenticationResultCode":"InvalidCredentials","brandLogoUri":"http:\/\/dev.virtualearth.net\/Branding\/logo_powered_by.png","copyright":"Copyright © 2017 Microsoft and its suppliers. All rights reserved. This API cannot be accessed and the content and any results may not be used, reproduced or transmitted in any manner without express written permission from Microsoft Corporation.","errorDetails":["Access was denied. You may have entered your credentials incorrectly, or you might not have access to the requested resource or operation."],"resourceSets":[],"statusCode":401,"statusDescription":"Unauthorized","traceId":"a32b43659ea6455d85fc0fb6a950c516|DB40080942|7.7.0.0|"})

**Comment by Beak-man** [comment]
This was addressed in PR #73
