### ISSUE TITLE
Region picking example does not work on mobile

### ISSUE THREAD

**Issue by eirizarry** [NASAWorldWind/WebWorldWind#721]
### Description
Found this bug in the Region Picking Example
### Steps to Reproduce

Run Region Picking example on mobile/tablet.

**Expected behavior:** 

Able to pick through by tapping on screen

**Actual behavior:** 

Nothing happens

**Reproduces how often:** 

100%

### Operating System and Version

n/a

### Additional Information

n/a

**Comment by pdavidc** [comment]
@eirizarry FYI: the title suggests to me that WorldWind's picking subsystem is broken, which as we know isn't the case.
