### ISSUE TITLE
KML classes are not defined in WorldWind global

### ISSUE THREAD

**Issue by emxsys** [NASAWorldWind/WebWorldWind#737]
I have a need to override the default attributes used in `KmlPlacemark` and `KmlStyle` but I am unable to do so because these classes are not declared in the `WorldWind` global.

    TypeError: WorldWind.KmlPlacemark is undefined.

**Comment by balhar-jakub** [comment]
I believe that the KML Classes should be part of the API, as it is possible and often really beneficial to overwrite parts of them and provide custom implementations. I wrote about how to do it here:
https://medium.com/@jakub_43881/kml-support-in-the-web-world-wind-23d94a9e5e58 but without them being part of the public API the instructions won't work. 

If we don't want to clutter the WorldWind space we can expose them on the KmlFile as a static properties? 

@AkeluX  @pdavidc  Any thoughts on your side?

**Comment by AkeluX** [comment]
We had a similar discussion about GeoJSON a while ago. The conclusion was roughly that one of the advantages of Web WorldWind is that it can be extended by the applications, e.g. tailoring of an existing shape beyond its attributes. Consequently, even internal classes should be exposed via the WorldWind namespace. @pdavidc do you agree?

**Comment by pdavidc** [comment]
@AkeluX Yes, I agree with this conclusion. Additionally, exposing all classes via the a single mechanism, the WorldWind global, is vital.

**Comment by pdavidc** [comment]
Closed via #759
