### ISSUE TITLE
GeoJSON doesn't support all standard WGS84 responses

### ISSUE THREAD

**Issue by balhar-jakub** [NASAWorldWind/WebWorldWind#751]
### Description

WGS Format produced by the GeoServer in the GeoJSON response to the WFS request produces the CRS, which isn't supported neither by Proj4 nor as a default version of the WGS84 CRS.

The Exception is thrown saying that the Projection isn't supported while the Polygon should be correctly displayed on the globe. 

### Steps to Reproduce

The produced CRS is urn:ogc:def:crs:EPSG::4326. The example GeoJSON is attached. 

[epsg4326.txt](https://github.com/NASAWorldWind/WebWorldWind/files/2111974/epsg4326.txt)

**Expected behavior:** 

The returned GeoJSON will be correctly interpreted and displayed on the layer. 

**Actual behavior:** 

The exception is thrown

**Reproduces how often:** 

Always

### Operating System and Version

Win 10 / Firefox, Chrome

**Comment by claudiaifrim** [comment]
A new alias must be added - see branch https://github.com/NASAWorldWind/WebWorldWind/tree/bug/%23751-geojson-wgs84
