### ISSUE TITLE
ScreenImages clipped in FireFox when zoomed in on the globe

### ISSUE THREAD

**Issue by emxsys** [NASAWorldWind/WebWorldWind#78]
ScreenImages, like the Compass and ViewControls are clipped when you zoom in on the globe in FireFox.  The issue does not occur in Chrome.

Following are three progressive screenshots from the SDK's Explorer app/demo demonstrating the issue.

### Screenshot 1
![image](https://cloud.githubusercontent.com/assets/191515/22863364/a07a9faa-f0f3-11e6-8b6c-c328135fd9ad.png)
_Zoomed out: No clipping_

### Screenshot 2
![image](https://cloud.githubusercontent.com/assets/191515/22863373/b2b60a2e-f0f3-11e6-851b-aaa59e987815.png)
_Zoomed in: Partial clipping of Compass and ViewControls_

### Screenshot 3
![image](https://cloud.githubusercontent.com/assets/191515/22863379/cef49796-f0f3-11e6-8b15-aecc9e50a391.png)
_Zoomed in further:  Compass and all but one of ViewControls are gone.  Note the PanControl ScreenImage remains. Interesting._

**Comment by PHPaul-ES** [comment]
To add a bit of extra info, when you decrease tilt below a certain amount, they pop out again

![tilt_notsomuch](https://cloud.githubusercontent.com/assets/26243874/24097777/ab50af74-0d67-11e7-95fa-5b9adb060132.png)
_Tilt a bit above zero (maybe around 20)_



![tilt_bunch](https://cloud.githubusercontent.com/assets/26243874/24097776/ab4ca3e8-0d67-11e7-9fa3-5e25943496e7.png)
_tilt closer to zero_

**Comment by emxsys** [comment]
The issue is related to depth testing being performed on screen images. The resolution is to disable depth testing in ScreenImage.beginDrawing() with a call to `gl.disable(gl.DEPTH_TEST)`.  

Example:
```
        ScreenImage.prototype.beginDrawing = function (dc) {
            var gl = dc.currentGlContext,
                         program;
            .
            .
            .

            // Turn off depth testing.
            gl.disable(gl.DEPTH_TEST);
        };
```

Why this is an issue only in Firefox is perplexing.
