### ISSUE TITLE
Problems with firefox 62.0

### ISSUE THREAD

**Issue by Sileo35** [NASAWorldWind/WebWorldWind#788]
Hello,
I have an issue only with firefox with the 3D sphere (the problem is still present with globe2d), it works correctly on chrome and i think it's since the 62.0. 

Step to reproduce :
- just launch firefox
- go to the basic example page 
https://files.worldwind.arc.nasa.gov/artifactory/apps/web/examples/BasicExample.html

![image](https://user-images.githubusercontent.com/33731447/45263145-57d1f500-b424-11e8-9da1-3458170e1c87.png)

**Comment by balhar-jakub** [comment]
I see the same issue as well.

**Comment by emxsys** [comment]
I have the same issue in Windows 10 using an NVidia GEForce graphics card. I updated the graphics driver but that did not resolve the problem.

Other programs have this problem too: https://support.mozilla.org/en-US/questions/1232932

**Comment by emxsys** [comment]
Here's another issued filed regarding Firefox update 62: [polygons not drawn or visible edges with Firefox 62](https://bugzilla.mozilla.org/show_bug.cgi?id=1489099)

**Comment by Sileo35** [comment]
Fixed in Firefox 62.0.2
