### ISSUE TITLE
Sometimes the annotation text is upside down.

### ISSUE THREAD

**Issue by servetg** [NASAWorldWind/WebWorldWind#79]
That's because the loading of texture coordinate matrix has been omitted.
A solution would be:
 1. texCoordMatrix initialization in Annotation's constructor
 line 115:
    // Internal use only. Intentionally not documented.
    this.texCoordMatrix = Matrix.fromIdentity();
 
 2. texCoordMatrix loading in Annotation.prototype.doDrawOrderedAnnotation, after program.loadTextureEnabled(gl, textureBound);
 line  513:
    this.texCoordMatrix.setToIdentity();
    this.texCoordMatrix.multiplyByTextureTransform(this.labelTexture);
    program.loadTextureMatrix(gl, this.texCoordMatrix);

**Comment by pdavidc** [comment]
Servet, Thanks for investigating this issue. The team has reviewed your proposal, and would like to get this fix in the repository. Would you please put together a fix and commit it to the develop branch?

**Comment by servetg** [comment]
Dave, I've made a pull request containing a fix for this bug.

**Comment by pdavidc** [comment]
Fix is in pull request #85
