### ISSUE TITLE
The globe isn't displayed in the Firefox 63 at all.

### ISSUE THREAD

**Issue by balhar-jakub** [NASAWorldWind/WebWorldWind#790]
### Description

With the update of the Firefox to the version 63 the whole Web World Wind stopped working. It isn't shown at all. 

It is visible at https://worldwind.arc.nasa.gov/web/get-started/#anchor

### Steps to Reproduce

1. Open the Get Started guide.

**Expected behavior:** [What you expect to happen]

The globe should be properly displayed. 

**Actual behavior:** [What actually happens]

Nothing is displayed in the canvas.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Operating System and Version

Windows 10 / Firefox 63

**Comment by emxsys** [comment]
@balhar-jakub  I concur.  The Explorer and other WebWW apps just display the view controls and other renderables in a corner of the canvas.

###### Screenshot: Explorer in Firefox 63
![image](https://user-images.githubusercontent.com/191515/47651568-d273e280-db40-11e8-9a39-b90d12ab311e.png)

**Comment by emxsys** [comment]
I filed this bug for Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1502889

**Comment by emxsys** [comment]
The folks at Mozilla have submitted a changeset for this bug and have marked it RESOLVED in build 65.
Changeset: https://hg.mozilla.org/mozilla-central/rev/79eaa3fb6632

**Comment by emxsys** [comment]
This issue has been resolved in Firefox v64.0. To update Firefox:

1. Open the Firefox menu
2. Select Help > About > Update
