### ISSUE TITLE
Worlwind install via npm error

### ISSUE THREAD

**Issue by migvf** [NASAWorldWind/WebWorldWind#796]
### Description

[I am trying to use WWD web in an Ionic project. Therefore i execute : npm install @worldwind/wordwind to get the Worlwind Component. I always get this error message:
Fatal error: Unable to find Gruntfile.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @nasaworldwind/worldwind@0.9.0 build: `grunt`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @nasaworldwind/worldwind@0.9.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
]

**Expected behavior:** [npm install finishes ok to build the project correctly]

**Reproduces how often:** [Always]

### Operating System and Version

- Windows 10,
- Node: 10.15.0
- npm: 6.4.1

**Comment by emxsys** [comment]
@migvf Were you able to resolve this issue?  Do you still need assistance?

**Comment by migvf** [comment]
@emxsys yes, finally i solved it. It was related with node version ( i have to downgrade it to 8.11.3). Thank you for replying and forgive me, i couldn't answer before.
