### ISSUE TITLE
WebWorldWind javascript online domain URL is expired and cannot access

### ISSUE THREAD

**Issue by bangph** [NASAWorldWind/WebWorldWind#800]
Hello,

When you visit http://worldwindserver.net/webworldwind/worldwind.min.js it will return 

`http://domain-registrar.storage.googleapis.com/expired.html?worldwindserver.net`

and error
`
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
</Error>
`
Can this one be fixed urgently as client using this library link is broken?

Thanks,

**Comment by emxsys** [comment]
@bangph You can get the current compiled library at https://files.worldwind.arc.nasa.gov/artifactory/web/0.9.0/worldwind.min.js
Of course, this will require a change in the client to use the new URL.

Example:
```
<script src="https://files.worldwind.arc.nasa.gov/artifactory/web/0.9.0/worldwind.min.js"
        type="text/javascript">
</script>```

**Comment by bangph** [comment]
@emxsys yes, I know I can update 1 link but it means all existing clients using WebWorldWind needs to update as well. Do you think it is good?

**Comment by emxsys** [comment]
@bangph Are/were you able to change the URL in your client?  Has the urgency been mitigated? 

Unfortunately, the `worldwindserver.net` domain is/was being paid for out-of-pocket by one of the developers.  Thus the shift to a NASA domain to ensure WorldWind's posterity.  

Note, the https://files.worldwind.arc.nasa.gov/artifactory/web/0.9.0/worldwind.min.js is a more current version than the old URL.  Another alternative is to host a copy of `worldwind.min.js` or the source on your own server to avoid the issue of changing URLs.  Of course, there are pros and cons to any approach. 

If there is an urgent use case, worldwindserver,net could be resurrected by said developer (still an out-of-pocket expense).

**Comment by emxsys** [comment]
@bangph et al. The worldwindserver.net domain has been renewed for another year.  It's end-of-life will be March 2, 2020.  Thanks for bringing this to our attention.
