### ISSUE TITLE
How to make WebWorldWind offline for elevation model?

### ISSUE THREAD

**Issue by bangph** [NASAWorldWind/WebWorldWind#807]
As project WebWorldWind is almost over, I need to make sure WebWorldWind will work offline with any requests to NASA server. The last one which I cannot figure out is the elevation model.

Basically, I want to disable it and accept that Earth is flat :) instead of these requests to get elevation model as **bil16** format.

[https://worldwind26.arc.nasa.gov/elev?service=WMS&request=GetMap&version=1.3.0&transparent=TRUE&layers=aster_v2&styles=&format=application/bil16&width=256&height=256&crs=EPSG:4326&bbox=22.5,-101.25,28.125,-95.625](url)

**Comment by PJHogan** [comment]
Band Pham,
Note "WorldWind Resources" on this web page,
https://worldwind.earth/

**Comment by bangph** [comment]
@PJHogan nice avatar :), the project is alive again, welcome back.
