### ISSUE TITLE
Sometimes SurfaceShapeTile updates incorrectly at different zoom levels

### ISSUE THREAD

**Issue by strikerM** [NASAWorldWind/WebWorldWind#81]
From what I see, this happens because tiles that are not needed in the current frame have their shapes cleared and at the same time prevSurfaceShapes will be set to the currentShapes.
When the tile is needed the updateIfNeeded method can not detect the difference between previous and current and the texture is never updated.

On possible fix would be to separate clearing shapes form setting the prevSurfaceShapes and setting 
prevSurfaceShapes in updateTexture.
The state key is also set in updateTexture.

https://gist.github.com/strikerM/2aa6748c2e28a95c7365072d69e7e6d4

**Comment by zglueck** [comment]
Fixed in 30cbb1dbffeb95f1a0ffd7d1b063c5cb69484697
