### ISSUE TITLE
Update "marked" dependency

### ISSUE THREAD

**Issue by markpet49** [NASAWorldWind/WebWorldWind#810]
Older versions of the node-js "marked" module have a vulnerability, upgrade dependencies to a repaired version. For reference:

A flaw was found in nodejs-marked versions from 0.5.0 to before 0.6.1. Affected versions of this package are vulnerable to Regular Expression Denial of Service (ReDoS). Input to the host variable is vulnerable when input contains parenthesis in link URIs, coupled with a high number of link tokens in a single line.

**Comment by PJHogan** [comment]
Those pesky DOS things were so innocent, 
usually just requiring a ReBoot.
Then the "O" got small and the beast "Re"-peatable.  
Apologies, just couldn't pass this one up! ;~}

**Comment by Beak-man** [comment]
PR #811 has been created to address this issue.

**Comment by Beak-man** [comment]
Addressed in PR #815

**Comment by PJHogan** [comment]
Yay!
