### ISSUE TITLE
Can't access standalone data archive

### ISSUE THREAD

**Issue by chakose** [NASAWorldWind/WebWorldWind#814]
Description
The standalone data archive is not accessible at: https://worldwind32.arc.nasa.gov/WebWorldWind-StandaloneData.tar.gz as referenced by the Standalone Tutorial (https://worldwind.arc.nasa.gov/web/tutorials/standalone-example/)

### Steps to Reproduce

1. Attempt download at https://worldwind32.arc.nasa.gov/WebWorldWind-StandaloneData.tar.gz 

**Expected behavior:** [What you expect to happen]
Access to download archive

**Actual behavior:** [What actually happens]
Receive "This site can't be reached" page

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Operating System and Version
Windows 10

**Comment by Beak-man** [comment]
Solved in PR #767
