### ISSUE TITLE
SurfaceShapeTile - the addAllSurfaceShapes method does nothing

### ISSUE THREAD

**Issue by strikerM** [NASAWorldWind/WebWorldWind#83]
The addAllSurfaceShapes method in SurfaceShapeTile just calls itself in a for loop, but doesn't do anything with the result.
I think the intention was to call this.addSurfaceShape(shape).

**Comment by pdavidc** [comment]
We've investigated this code and found that it's unnecessary. Commit 8ab0f91 removes the unnecessary code and resolves this issue.
