### ISSUE TITLE
Poor error messages in proj4-src.js

### ISSUE THREAD

**Issue by Cazadorro** [NASAWorldWind/WebWorldWind#835]
I would submit a pull request myself, but I only encountered these issues helping someone else who uses this library, I don't use NWW myself at the moment, and don't understand the javascript build environment.

Recently I was helping debug someone's code that used the latest minified NWW release as of 8/17/2020.
This line https://github.com/NASAWorldWind/WebWorldWind/blob/20a5a0cce09bde159cb64d3a5136190fc4d52e6c/src/util/proj4-src.js#L1351 caused a couple hours of headache.  

The issue was our geotiff was in EPSG 26.... or something, and all we saw was EPSG:26... as an uncaught error.  Prior to today neither of us even knew what EPSG was (we were used to WSG84 NAD83 etc...), so we had assumed it was some odd error code.  So we spent hours with no clue on what the issue was until we could isolate the place that actually spawned the error.  

The code currently only takes the string of the spatial reference code and just dumps it out with no other context, I suggest that the following code:

```
 callback = callback || function(error){
                if(error){
                    throw error;
                }
            };
        var json = parse(srsCode);
        if(typeof json !== 'object'){
            callback(srsCode);
            return;
        }
        var ourProj = Projection$1.projections.get(json.projName);
        if(!ourProj){
            callback(srsCode);
            return;
        }

```

get replaced with:

```
 callback = callback || function(error){
                if(error){
                    throw ("unknown spacial reference system code found: " + error);
                }
            };
        var json = parse(srsCode);
        if(typeof json !== 'object'){
            callback(srsCode);
            return;
        }
        var ourProj = Projection$1.projections.get(json.projName);
        if(!ourProj){
            callback(srsCode);
            return;
        }

```

**Comment by Beak-man** [comment]
Hi @Cazadorro, thanks for your detailed report.

Proj4 is one of our external dependencies, which, given our current module loader, is not being managed by npm.
[We have a branch](https://github.com/NASAWorldWind/WebWorldWind/tree/enhancement/Webpack_bundler_migration) where a new module loader is being tested and our external dependencies are updated in there, but in the meantime, you can try to use a newer version of proj4 and see if your issue persists, so you don't have to use what is a essentially a fork of Proj4:

https://github.com/proj4js/proj4js

We'll look into manually updating it to our develop branch in the meantime.

**Comment by Cazadorro** [comment]
@Beak-man Thanks, that makes sense, looked completely different from the rest of the code base, didn't realize it was an external dependency.
