### ISSUE TITLE
Hosted library files missing for 0.10.0 release

### ISSUE THREAD

**Issue by smithfred** [NASAWorldWind/WebWorldWind#855]
### Description

https://github.com/NASAWorldWind/WebWorldWind/releases/tag/v0.10.0 links to https://files.worldwind.arc.nasa.gov/artifactory/web/0.10.0/, which doesn't exist.

**Comment by Beak-man** [comment]
Hello @smithfred . The files are up and running now. Give them a try and let us know if you encounter any issues.
