### ISSUE TITLE
Standalone example out of date

### ISSUE THREAD

**Issue by smithfred** [NASAWorldWind/WebWorldWind#857]
### Description

https://worldwind.arc.nasa.gov/web/tutorials/standalone-example/ has the following:

```javascript
var elevationModel = new WorldWind.EarthRestElevationModel(null, "../standalonedata/Earth/DTED0");
var wwd = new WorldWind.WorldWindow("canvasOne", elevationModel);
```

For 0.10.0, this should now be:

```javascript
var elevationCoverage = new WorldWind.EarthRestElevationCoverage("../standalonedata/Earth/DTED0");
var elevationModel = new WorldWind.ElevationModel();
elevationModel.addCoverage(elevationCoverage);
var wwd = new WorldWind.WorldWindow("canvasOne", elevationModel);
```

**Comment by Beak-man** [comment]
Hi @smithfred, thanks for reporting this.
We added your update to the code shown in the website and we renamed the "Standalone" example as "Offline". It can now be found here:
https://worldwind.arc.nasa.gov/web/tutorials/offline-example/
