### ISSUE TITLE
npm module does not work with webpack

### ISSUE THREAD

**Issue by jmsbrett** [NASAWorldWind/WebWorldWind#881]
[npm_webpack.txt](https://github.com/NASAWorldWind/WebWorldWind/files/8781337/npm_webpack.txt)

**Comment by Beak-man** [comment]
Hi @jmsbrett. There are a couple of community examples on the usage of WorldWind within React. Check if these help:

https://github.com/Beak-man/worldwind-react
https://github.com/WorldWindEarth/worldwind-react-globe

**Comment by jmsbrett** [comment]
Thank you for the fast response. I will take a look at those examples again. Really wanted to stay within the official NASA ecosystem.

**Comment by Beak-man** [comment]
You're welcome. Those examples are old, however. I'll test with a new create-react-app instance.

**Comment by jmsbrett** [comment]
I got it working after looking at your example with a new create-react-app instance. Thank you for the example. I had not seen this example until our chat
