### ISSUE TITLE
StyleResolver.handleRemoteStyle is not defined when adding KML

### ISSUE THREAD

**Issue by jaybarra** [NASAWorldWind/WebWorldWind#94]
[KML_Samples_all_visible.zip](https://github.com/NASAWorldWind/WebWorldWind/files/828554/KML_Samples_all_visible.zip)

In attempting to add KML I am receiving the following error

```javascript
Uncaught TypeError: StyleResolver.handleRemoteStyle is not a function
    at worldwind.js:64062
```
The errors are thrown when the mouse moves over the canvas containing the WorldWindow

**Comment by QingMings** [comment]
#80 ,

**Comment by AkeluX** [comment]
@jaybarra we've merged this fix into the develop branch. Could you tell us if this addresses your issue?

**Comment by AkeluX** [comment]
Already confirmed by another user. Let us know if this isn't the case for you.
